import type { DistrictDef, PlaysetDef } from '../types';

// Every playset in the Cosmic Bubble asset stack, arranged into three districts that
// match the Stitch world-map screens: "Starry Island City" (the island map),
// "Transit & Market Plaza" (the transit map) and "Star Studios" (the four hidden
// studio/secret playsets that have no map pin and float as bubbles instead).
//
// Hotspot x/y are percentages of the scene image (1200×896, 4:3).

const H = (id: string, x: number, y: number, emoji: string, label: string, reaction: string) => ({ id, x, y, emoji, label, reaction });
const A = (id: string, emoji: string, label: string, reaction: string) => ({ id, emoji, label, reaction });
const T = (id: string, label: string) => ({ id, label });
const P = (id: string, emoji: string, name: string, sub: string, rarity: 1 | 2 | 3 | 4) => ({ id, emoji, name, sub, rarity });

export const PLAYSETS: PlaysetDef[] = [
    // ─── Starry Island City ──────────────────────────────────────────────────
    {
        key: 'sweet_lilac_bungalow',
        name: 'Sweet Lilac Bungalow',
        shortName: 'Bungalow',
        tag: 'COZY DUPLEX',
        subtitle: 'Cloud Plot 04 • Mezzanine & Patio',
        blurb: 'Cosy bedrooms, kitchen, backyard & flowers',
        status: 'Duplex #4 & #5',
        district: 'island',
        category: 'homes',
        emoji: '🏡',
        tone: 'pink',
        unlockCost: 0,
        image: 'sweet_lilac_bungalow',
        ambience: ['💡 Bedtime Lamp: ON', '☕ Kettle: STEAMING'],
        hotspots: [
            H('loft', 52, 26, '🌙', 'Star Loft', 'Minni is cozy in pajamas! Tap the sofa to curl up.'),
            H('lounge', 26, 62, '🛋️', 'Marshmallow Lounge', 'The sofa is soooo squishy. Five more minutes!'),
            H('kitchen', 75, 60, '🍳', 'Pastel Kitchen', 'Star toast is popping! Who wants jam?'),
            H('garden', 80, 80, '🌸', 'Cloud Garden', 'The candy fern says hello. It smiles back!'),
        ],
        actions: [
            A('snooze', '💤', 'Snooze', 'Zzz… Minni dreams of bubble planets.'),
            A('cocoa', '☕', 'Star Cocoa', 'Mmm, warm cocoa with marshmallow moons!'),
            A('cushions', '🧹', 'Cushions', 'Cushions fluffed! The lounge is ready for guests.'),
        ],
        routine: {
            title: 'Bedtime Star Routine',
            subtitle: 'Tuck Minni into the Cloud Bed!',
            badge: 'Sleepy Star Badge 🌙',
            tasks: [T('duvet', 'Cloud duvet fluffed'), T('nightlight', 'Starlight nightlight lit'), T('story', 'Bedtime story read')],
        },
        props: [
            P('cloud_bed', '🛏️', 'Star Cloud Bed', 'Fluffy Sleep', 4),
            P('vanity', '🪞', 'Lilac Vanity Desk', 'Studio Glow', 3),
            P('sofa', '🛋️', 'Marshmallow Sofa', 'Squishy Pink', 2),
            P('moon_lamp', '🌙', 'Moon Table Lamp', 'Warm Gold', 1),
            P('toaster', '🍞', 'Starlight Toaster', 'Pastel Toast', 1),
            P('fern', '🪴', 'Potted Candy Fern', 'Botanical', 1),
        ],
    },
    {
        key: 'starlight_school_observatory',
        name: 'Starlight School & Observatory',
        shortName: 'School',
        tag: 'SCIENCE LAB',
        subtitle: 'Orbit Sector 07 • Dome Telescope',
        blurb: 'Cosmic science & star gazing telescope',
        status: '4 Friends inside',
        district: 'island',
        category: 'community',
        emoji: '🔭',
        tone: 'violet',
        unlockCost: 0,
        image: 'starlight_school_observatory',
        ambience: ['🔭 Telescope: ALIGNED', '🧪 Potions: BUBBLING'],
        hotspots: [
            H('telescope', 70, 22, '🔭', 'Brass Telescope', 'I can see a bubble planet! It has rings made of candy!'),
            H('lab', 30, 40, '🧪', 'Potion Lab', 'Careful… the purple potion fizzes when you giggle.'),
            H('desks', 45, 70, '📚', 'Student Desks', 'Today\'s lesson: how many stars fit in a soda can?'),
            H('globe', 78, 66, '🌍', 'Celestial Globe', 'Spin the globe! Where should we fly next?'),
        ],
        actions: [
            A('stargaze', '✨', 'Stargaze', 'Three shooting stars! Make a wish, quick!'),
            A('experiment', '🧪', 'Experiment', 'POP! The potion turned into rainbow bubbles.'),
            A('bell', '🔔', 'Ring Bell', 'Ding ding! Recess on the moon deck!'),
        ],
        routine: {
            title: 'Star Science Routine',
            subtitle: 'Finish today\'s cosmic lesson!',
            badge: 'Little Astronomer Badge 🔭',
            tasks: [T('chart', 'Star chart drawn'), T('potion', 'Rainbow potion mixed'), T('planet', 'New planet named')],
        },
        props: [
            P('telescope', '🔭', 'Mini Telescope', 'Brass Dome', 3),
            P('globe', '🪐', 'Celestial Globe', 'Spins!', 2),
            P('beaker', '🧪', 'Fizzy Beaker', 'Potion Lab', 1),
            P('books', '📚', 'Star Books', 'Reading Nook', 1),
            P('rocket_model', '🚀', 'Rocket Model', 'Science Fair', 2),
            P('chalkboard', '🧮', 'Moon Chalkboard', 'Lesson Time', 1),
        ],
    },
    {
        key: 'cozy_heart_hospital',
        name: 'Cozy Heart Hospital',
        shortName: 'Hospital',
        tag: 'HEALTH CENTER',
        subtitle: 'Pediatric Clinic • Open 24/7',
        blurb: 'Emergency nursery, X-ray & pet care',
        status: 'Open 24/7',
        district: 'island',
        category: 'community',
        emoji: '🏥',
        tone: 'pink',
        unlockCost: 120,
        image: 'cozy_heart_hospital',
        ambience: ['❤️ Heart Monitor: BEEP', '🍼 Nursery: QUIET'],
        hotspots: [
            H('checkup', 30, 45, '🩺', 'Checkup Bed', 'Say ahh! Everything looks sparkly-healthy.'),
            H('cradle', 68, 36, '🌙', 'Moon Cradle', 'Shh… the baby stars are sleeping.'),
            H('xray', 78, 70, '🦴', 'Alien X-Ray', 'Whoa, three hearts! That\'s totally normal for aliens.'),
            H('pharmacy', 22, 74, '💊', 'Candy Pharmacy', 'One star vitamin a day keeps the grumps away.'),
        ],
        actions: [
            A('bandage', '🩹', 'Bandage', 'All patched up with a glitter bandage!'),
            A('checkup', '🩺', 'Checkup', 'Heartbeat sounds like a tiny drum. Perfect!'),
            A('lullaby', '🎵', 'Lullaby', 'Twinkle twinkle… the nursery yawns.'),
        ],
        routine: {
            title: 'Doctor Star Routine',
            subtitle: 'Help every patient feel better!',
            badge: 'Kind Heart Badge ❤️',
            tasks: [T('temp', 'Temperature taken'), T('bandage', 'Glitter bandage applied'), T('lollipop', 'Brave lollipop given')],
        },
        props: [
            P('bed', '🛏️', 'Checkup Bed', 'Soft Pink', 2),
            P('cradle', '🌙', 'Moon Cradle', 'Nursery', 3),
            P('teddy', '🧸', 'Get-Well Teddy', 'Cuddly', 1),
            P('kit', '🩺', 'Doctor Kit', 'Stethoscope', 1),
            P('wheelchair', '🦽', 'Star Wheelchair', 'Zoomy', 2),
            P('balloon', '🎈', 'Cheer Balloon', 'Heart Shaped', 1),
        ],
    },
    {
        key: 'cosmic_dome_stadium',
        name: 'Cosmic Dome Stadium',
        shortName: 'Stadium',
        tag: 'SPORTS',
        subtitle: 'Roller Derby Arena • Zero-G Field',
        blurb: 'Zero-G soccer & neon roller skate ring',
        status: 'Roller Derby Live',
        district: 'island',
        category: 'community',
        emoji: '🏟️',
        tone: 'mint',
        unlockCost: 150,
        image: 'cosmic_dome_stadium',
        ambience: ['🛼 Derby: LIVE', '📣 Crowd: LOUD'],
        hotspots: [
            H('track', 40, 60, '🛼', 'Rainbow Track', 'Wheee! Minni skates a full loop in zero gravity!'),
            H('goal', 75, 40, '⚽', 'Zero-G Goal', 'GOOOAL! The ball floated in slow motion.'),
            H('board', 50, 18, '🏆', 'Scoreboard', 'Home team: 3. Comets: 3. Cosmic tie!'),
            H('bleachers', 18, 40, '📣', 'Bleachers', 'The crowd does the wave… in space it takes a while.'),
        ],
        actions: [
            A('kick', '⚽', 'Kick Off', 'Boom! The ball bounces off the dome glass.'),
            A('skate', '🛼', 'Skate Lap', 'Zoom zoom! Fastest lap of the day.'),
            A('cheer', '📣', 'Cheer', 'GO MINNI GO! The bleachers glow pink.'),
        ],
        routine: {
            title: 'Champion Routine',
            subtitle: 'Warm up, play, celebrate!',
            badge: 'Gold Whistle Badge 🏅',
            tasks: [T('stretch', 'Space stretches done'), T('lap', 'Derby lap finished'), T('trophy', 'Trophy polished')],
        },
        props: [
            P('ball', '⚽', 'Bubble Ball', 'Zero-G', 1),
            P('trophy', '🏆', 'Star Trophy', 'Shiny', 3),
            P('skates', '🛼', 'Neon Skates', 'Speedy', 2),
            P('cone', '🔶', 'Training Cone', 'Practice', 1),
            P('flag', '🚩', 'Team Flag', 'Go Comets!', 1),
            P('whistle', '🎽', 'Coach Jersey', 'Number 7', 2),
        ],
    },
    {
        key: 'mega_shopping_mall',
        name: 'Mega Shopping Mall',
        shortName: 'Mall',
        tag: 'SHOPPING',
        subtitle: '3 Floors • Space Galleria',
        blurb: 'Fashion boutique, boba shop & food court',
        status: '3 Floors of Fashion',
        district: 'island',
        category: 'shopping',
        emoji: '🛍️',
        tone: 'violet',
        unlockCost: 150,
        image: 'mega_shopping_mall',
        ambience: ['🛗 Escalators: GLIDING', '🧋 Boba: SHAKING'],
        hotspots: [
            H('boutique', 25, 40, '👗', 'Star Boutique', 'Ooh, a sparkle cape! It matches my helmet.'),
            H('diner', 70, 30, '🍔', 'Starlite Diner', 'Milkshake with a moon on top, please!'),
            H('boba', 55, 62, '🧋', 'Boba Bar', 'Galaxy boba! The pearls glow in the dark.'),
            H('cosmetics', 78, 72, '💄', 'Cosmetics Bar', 'Glitter cheeks activated. Fabulous!'),
        ],
        actions: [
            A('shop', '🛍️', 'Window Shop', 'So many shiny things! Just looking… for now.'),
            A('escalator', '🛗', 'Ride Up', 'Wheee, the escalator floats to floor three!'),
            A('snack', '🍟', 'Snack Time', 'Star fries with rainbow ketchup. Yum!'),
        ],
        routine: {
            title: 'Shopping Spree Routine',
            subtitle: 'Visit every floor of the galleria!',
            badge: 'Style Star Badge 👑',
            tasks: [T('floor1', 'Boutique visited'), T('floor2', 'Boba tasted'), T('floor3', 'Food court explored')],
        },
        props: [
            P('mannequin', '👗', 'Sparkle Dress', 'Boutique', 3),
            P('boba', '🧋', 'Galaxy Boba', 'Glow Pearls', 1),
            P('bag', '🛍️', 'Shopping Bag', 'Full!', 1),
            P('milkshake', '🥤', 'Moon Milkshake', 'Diner', 1),
            P('mirror', '🪞', 'Selfie Mirror', 'Cosmetics', 2),
            P('gift', '🎁', 'Mystery Gift', 'Wrapped', 2),
        ],
    },
    {
        key: 'star_soda_arcade',
        name: 'Star Soda Arcade',
        shortName: 'Arcade',
        tag: 'MINI GAMES',
        subtitle: 'Game Zone • Ticket Shop',
        blurb: 'Claw machines, dance pad & ticket shop',
        status: 'High Scores',
        district: 'island',
        category: 'shopping',
        emoji: '🕹️',
        tone: 'aqua',
        unlockCost: 0,
        image: 'star_soda_arcade',
        ambience: ['🕹️ Machines: ON', '🎟️ Tickets: 9,420'],
        hotspots: [
            H('claw', 22, 40, '🧸', 'Claw Machine', 'Almost… almost… GOT IT! A jelly plushie!'),
            H('dance', 50, 68, '💃', 'Dance Pad', 'Left, right, spin! Perfect combo!'),
            H('pinball', 75, 40, '🎯', 'Pinball', 'Ding ding ding! Multiball mode!'),
            H('prizes', 80, 74, '🎟️', 'Prize Counter', 'Enough tickets for the giant star plush!'),
        ],
        actions: [
            A('play', '🎮', 'Play', 'New high score! The machine sings a little song.'),
            A('dance', '🕺', 'Dance', 'Disco lights on! Everybody wiggle!'),
            A('tickets', '🎟️', 'Cash Tickets', 'Tickets traded for a glow-in-the-dark yoyo.'),
        ],
        routine: {
            title: 'Arcade Champ Routine',
            subtitle: 'Beat every machine once!',
            badge: 'Pixel Star Badge 🎮',
            tasks: [T('claw', 'Claw prize won'), T('dance', 'Dance combo landed'), T('pinball', 'Pinball jackpot hit')],
        },
        props: [
            P('claw', '🧸', 'Claw Plushie', 'Jelly Soft', 2),
            P('cabinet', '🕹️', 'Retro Cabinet', 'Neon', 3),
            P('hockey', '🏒', 'Air Hockey', 'Slidey', 2),
            P('token', '🪙', 'Star Token', 'Shiny', 1),
            P('soda', '🥤', 'Star Soda', 'Fizzy', 1),
            P('yoyo', '🪀', 'Glow Yoyo', 'Prize', 1),
        ],
    },
    {
        key: 'rainbow_playground',
        name: 'Rainbow Playground',
        shortName: 'Playground',
        tag: 'OUTDOOR PARK',
        subtitle: 'Cloud Island • Family Chill',
        blurb: 'Big slides, seesaws, sandbox & ice cream van',
        status: 'Family Chill',
        district: 'island',
        category: 'community',
        emoji: '🎠',
        tone: 'gold',
        unlockCost: 0,
        image: 'rainbow_playground',
        ambience: ['☀️ Weather: SUNNY', '🍦 Ice Cream: FRESH'],
        hotspots: [
            H('slide', 30, 40, '🌈', 'Rainbow Slide', 'WHEEEEE! Down the rainbow and into the clouds!'),
            H('carousel', 68, 36, '🎠', 'Star Carousel', 'Round and round on a flying star horse!'),
            H('sandbox', 50, 74, '🏖️', 'Sandbox', 'Building a moon castle with a bubble moat.'),
            H('trampoline', 80, 70, '🍄', 'Mushroom Trampoline', 'Boing! Boing! Minni touched a cloud!'),
        ],
        actions: [
            A('swing', '🎢', 'Swing', 'Higher! Higher! Minni can see the whole island!'),
            A('icecream', '🍦', 'Ice Cream', 'Triple scoop: nebula, comet crunch and bubblegum.'),
            A('picnic', '🧺', 'Picnic', 'Sandwiches shaped like stars. Naturally.'),
        ],
        routine: {
            title: 'Sunny Day Routine',
            subtitle: 'Play, snack and rest!',
            badge: 'Sunshine Badge ☀️',
            tasks: [T('slide', 'Slide ridden 3 times'), T('castle', 'Moon castle built'), T('rest', 'Cloud nap taken')],
        },
        props: [
            P('slide', '🛝', 'Mini Slide', 'Rainbow', 3),
            P('seesaw', '⚖️', 'Seesaw', 'Up & Down', 2),
            P('bucket', '🪣', 'Sand Bucket', 'Sandbox', 1),
            P('kite', '🪁', 'Star Kite', 'Windy', 1),
            P('icecream', '🍦', 'Ice Cream', 'Triple Scoop', 1),
            P('ball', '🏐', 'Beach Ball', 'Bouncy', 1),
        ],
    },
    {
        key: 'empire_builder_plot',
        name: 'Empire Builder Plot',
        shortName: 'Build Lot',
        tag: 'SPECIAL LOT',
        subtitle: 'Plot #01 • Creative Sandbox',
        blurb: 'Custom villa, star pool & garden',
        status: 'Ready to Build',
        district: 'island',
        category: 'homes',
        emoji: '🏰',
        tone: 'gold',
        unlockCost: 200,
        image: 'empire_builder_plot',
        ambience: ['🏗️ Crane: READY', '📐 Blueprints: 3'],
        hotspots: [
            H('crane', 70, 28, '🏗️', 'Pastel Crane', 'Lifting a marshmallow wall into place. Steady…'),
            H('table', 28, 48, '📐', 'Drafting Table', 'Blueprint idea: a slide from the bedroom to the pool!'),
            H('pool', 55, 72, '🏊', 'Star Pool', 'Splash! The water is fizzy like soda.'),
            H('garden', 20, 76, '🌷', 'Garden Bed', 'Planting glow tulips. They light up at night!'),
        ],
        actions: [
            A('build', '🔨', 'Build', 'Wall up! The villa grows another storey.'),
            A('paint', '🎨', 'Paint', 'Bubblegum pink with cyan trim. Gorgeous!'),
            A('plant', '🌱', 'Plant', 'Star seeds planted. Water with sparkle juice.'),
        ],
        routine: {
            title: 'Master Builder Routine',
            subtitle: 'Raise the star villa!',
            badge: 'Hard Hat Badge 🏗️',
            tasks: [T('blueprint', 'Blueprint drawn'), T('walls', 'Walls stacked'), T('roof', 'Star roof placed')],
        },
        props: [
            P('crane', '🏗️', 'Mini Crane', 'Lifts!', 4),
            P('bricks', '🧱', 'Candy Bricks', 'Stackable', 1),
            P('pool', '🏊', 'Star Pool', 'Splashy', 3),
            P('fence', '🪵', 'Pastel Fence', 'Garden', 1),
            P('tulip', '🌷', 'Glow Tulip', 'Botanical', 1),
            P('roof', '🏠', 'Star Roof', 'Finishing', 2),
        ],
    },

    // ─── Transit & Market Plaza ──────────────────────────────────────────────
    {
        key: 'cosmic_bus_terminal',
        name: 'Cosmic Bus Terminal',
        shortName: 'Bus Depot',
        tag: 'TRANSIT HUB',
        subtitle: 'Boarding Bay 3 • Waiting Lounge',
        blurb: 'Board double-decker star buses, luggage lockers & ticket punch',
        status: '3 Buses Arriving',
        district: 'transit',
        category: 'travel',
        emoji: '🚌',
        tone: 'aqua',
        unlockCost: 0,
        image: 'cosmic_bus_terminal',
        ambience: ['🚌 Next Bus: 2 MIN', '🎫 Gate: OPEN'],
        hotspots: [
            H('bus', 35, 55, '🚌', 'Star Bus', 'Top deck, front seat! Best view of the nebula.'),
            H('board', 60, 22, '🛰️', 'Departure Board', 'Next stop: Bakery Moon, then Rainbow Station.'),
            H('lockers', 78, 50, '🧳', 'Luggage Lockers', 'Locker 12 has a snack stash. Don\'t tell.'),
            H('vending', 82, 76, '🥤', 'Vending Machine', 'Galaxy fizz, ka-chunk! It glows purple.'),
        ],
        actions: [
            A('ticket', '🎫', 'Punch Ticket', 'Click! Ticket punched with a star shape.'),
            A('board', '🚌', 'Board Bus', 'All aboard! The doors fold shut with a hiss.'),
            A('wait', '🪑', 'Lounge', 'Galaxy pillows are the comfiest waiting spot.'),
        ],
        routine: {
            title: 'Traveller Routine',
            subtitle: 'Catch the star bus on time!',
            badge: 'Star Commuter Badge 🎫',
            tasks: [T('ticket', 'Ticket bought'), T('locker', 'Bag stored'), T('bus', 'Bus boarded')],
        },
        props: [
            P('bus', '🚌', 'Toy Star Bus', 'Double Decker', 4),
            P('suitcase', '🧳', 'Galaxy Suitcase', 'Packed', 1),
            P('bench', '🪑', 'Lounge Seat', 'Plush', 1),
            P('sign', '🪧', 'Route Sign', 'Bay 3', 1),
            P('drink', '🥤', 'Galaxy Fizz', 'Vending', 1),
            P('clock', '🕰️', 'Depot Clock', 'Tick Tock', 2),
        ],
    },
    {
        key: 'rainbow_railway_station',
        name: 'Grand Rainbow Railway Station',
        shortName: 'Railway',
        tag: 'EXPRESS LINE',
        subtitle: 'Platform 1 • Bubble Train',
        blurb: 'Ride the high-speed maglev bubble train across cosmic nebulae',
        status: 'Bubble Train on Platform',
        district: 'transit',
        category: 'travel',
        emoji: '🚂',
        tone: 'violet',
        unlockCost: 120,
        image: 'rainbow_railway_station',
        ambience: ['🚆 Train: BOARDING', '🕰️ Clock Tower: 3:00'],
        hotspots: [
            H('train', 62, 42, '🚆', 'Bubble Train', 'Whoosh! The train floats above the rainbow rails.'),
            H('clock', 30, 20, '🕰️', 'Clock Tower', 'Bong! Bong! Three o\'clock — cookie time.'),
            H('platform', 40, 66, '🛤️', 'Platform 1', 'Mind the gap… it\'s full of stars!'),
            H('luggage', 15, 60, '🧳', 'Luggage Racks', 'Whose suitcase is glowing? Ooh, mine!'),
        ],
        actions: [
            A('whistle', '📯', 'Whistle', 'Toot toot! Departing for Nebula Nine.'),
            A('ride', '🚆', 'Ride', 'The windows show comets zooming past. Amazing!'),
            A('snack', '🍪', 'Snack Cart', 'Rainbow cookie from the cart. Crunch!'),
        ],
        routine: {
            title: 'Conductor Routine',
            subtitle: 'Get the bubble train rolling!',
            badge: 'Conductor Cap Badge 🎩',
            tasks: [T('tickets', 'Tickets checked'), T('whistle', 'Whistle blown'), T('depart', 'Train departed')],
        },
        props: [
            P('train', '🚂', 'Toy Bubble Train', 'Maglev', 4),
            P('signal', '🚦', 'Rail Signal', 'Green!', 1),
            P('cart', '🛒', 'Snack Cart', 'Cookies', 2),
            P('bench', '🪑', 'Platform Bench', 'Waiting', 1),
            P('map', '🗺️', 'Route Map', 'All Lines', 1),
            P('lantern', '🏮', 'Station Lantern', 'Glowing', 2),
        ],
    },
    {
        key: 'star_gas_car_wash',
        name: 'Star Gas, EV & Car Wash',
        shortName: 'Gas & Wash',
        tag: 'PIT STOP',
        subtitle: 'Wash Bay • EV Charging Hub',
        blurb: 'Neon fuel pumps, solar plugs & bubbly car wash sponge tunnel',
        status: 'Wash Bay Open',
        district: 'transit',
        category: 'service',
        emoji: '⛽',
        tone: 'teal',
        unlockCost: 100,
        image: 'star_gas_car_wash',
        ambience: ['🫧 Foam: MAXIMUM', '⚡ Charger: 80%'],
        hotspots: [
            H('pump', 30, 45, '⛽', 'Neon Pump', 'Fill her up with star soda fuel!'),
            H('tunnel', 68, 40, '🫧', 'Foam Tunnel', 'Bubbles everywhere! The car giggles.'),
            H('charger', 22, 74, '⚡', 'EV Charger', 'Zap zap! Charged by sunshine.'),
            H('garage', 78, 74, '🔧', 'Pit-Stop Garage', 'New tyres, extra bouncy.'),
        ],
        actions: [
            A('wash', '🧽', 'Wash', 'Scrub-a-dub! Sparkling clean.'),
            A('fuel', '⛽', 'Fuel Up', 'Glug glug glug… full tank of fizz!'),
            A('honk', '📣', 'Honk', 'Beep beep! The car sings back.'),
        ],
        routine: {
            title: 'Pit Crew Routine',
            subtitle: 'Get the car race-ready!',
            badge: 'Speedy Sponge Badge 🧽',
            tasks: [T('fuel', 'Tank filled'), T('wash', 'Foam wash done'), T('shine', 'Windows polished')],
        },
        props: [
            P('car', '🚗', 'Pastel Car', 'Vroom', 3),
            P('sponge', '🧽', 'Giant Sponge', 'Bubbly', 1),
            P('pump', '⛽', 'Mini Pump', 'Neon', 2),
            P('tyre', '🛞', 'Bouncy Tyre', 'Garage', 1),
            P('cone', '🚧', 'Wash Cone', 'Careful', 1),
            P('scooter', '🛵', 'Pastel Moped', 'Delivery', 2),
        ],
    },
    {
        key: 'fresh_farmers_market',
        name: 'Starlight Fresh Farmers Market',
        shortName: 'Market',
        tag: 'ORGANIC FARM',
        subtitle: 'Candy-Striped Stalls • Juice Stand',
        blurb: 'Crisp cosmic carrots, glowing stardust berries, scales & cashier!',
        status: 'Daily Harvest',
        district: 'transit',
        category: 'food',
        emoji: '🥕',
        tone: 'mint',
        unlockCost: 100,
        image: 'fresh_farmers_market',
        ambience: ['🍓 Berries: GLOWING', '⚖️ Scales: READY'],
        hotspots: [
            H('stall', 35, 45, '🍎', 'Fruit Stall', 'Star fruit! It actually twinkles.'),
            H('scales', 62, 50, '⚖️', 'Produce Scales', 'Three glow-berries weigh… one moonbeam.'),
            H('juice', 78, 30, '🧃', 'Juice Stand', 'Fresh nebula juice, extra sparkly!'),
            H('crates', 25, 74, '📦', 'Wooden Crates', 'Cosmic carrots, still warm from the sun.'),
        ],
        actions: [
            A('shop', '🧺', 'Fill Basket', 'Basket full of rainbow veggies!'),
            A('taste', '🍓', 'Taste', 'Mmm! Stardust berries pop like fizz.'),
            A('pay', '🪙', 'Pay', 'Ka-ching! Thank you, come again!'),
        ],
        routine: {
            title: 'Market Day Routine',
            subtitle: 'Shop the whole market!',
            badge: 'Fresh Picker Badge 🥕',
            tasks: [T('fruit', 'Star fruit picked'), T('weigh', 'Veggies weighed'), T('juice', 'Juice tasted')],
        },
        props: [
            P('basket', '🧺', 'Market Basket', 'Woven', 1),
            P('carrot', '🥕', 'Cosmic Carrot', 'Crunchy', 1),
            P('berries', '🍓', 'Glow Berries', 'Sparkly', 1),
            P('scales', '⚖️', 'Brass Scales', 'Weigh It', 2),
            P('juice', '🧃', 'Nebula Juice', 'Fresh', 1),
            P('stall', '🏪', 'Mini Stall', 'Striped', 3),
        ],
    },
    {
        key: 'sweet_moon_bakery',
        name: 'Sweet Moon Bakery & Café',
        shortName: 'Bakery',
        tag: 'FRESHLY BAKED',
        subtitle: 'Star Café • Oven Warm',
        blurb: 'Star bagels, rainbow croissants, cinnamon rolls & hot cocoa tap',
        status: 'Oven Warm',
        district: 'transit',
        category: 'food',
        emoji: '🥐',
        tone: 'gold',
        unlockCost: 0,
        image: 'sweet_moon_bakery',
        ambience: ['🔥 Oven: WARM', '☕ Espresso: FIZZING'],
        hotspots: [
            H('display', 35, 50, '🍩', 'Pastry Case', 'Star donuts with galaxy sprinkles. Take two!'),
            H('oven', 70, 40, '🔥', 'Moon Oven', 'Ding! The croissants are rainbow-golden.'),
            H('espresso', 78, 68, '☕', 'Soda Espresso', 'Fizzy cocoa with a marshmallow moon.'),
            H('booth', 20, 74, '🪑', 'Cosy Booth', 'Window seat! Watching comets go by.'),
        ],
        actions: [
            A('bake', '🧁', 'Bake', 'Whisk, pour, bake… star cupcakes!'),
            A('serve', '🍽️', 'Serve', 'Order up! Table three gets the macarons.'),
            A('taste', '🍩', 'Taste', 'Galaxy macaron. Crunchy, then fluffy. Perfect.'),
        ],
        routine: {
            title: 'Baker Routine',
            subtitle: 'Open the café for the morning rush!',
            badge: 'Sugar Star Badge 🧁',
            tasks: [T('dough', 'Dough kneaded'), T('bake', 'Donuts baked'), T('serve', 'First customer served')],
        },
        props: [
            P('donut', '🍩', 'Star Donut', 'Sprinkles', 1),
            P('croissant', '🥐', 'Rainbow Croissant', 'Flaky', 1),
            P('cake', '🎂', 'Moon Cake', 'Party!', 3),
            P('mug', '☕', 'Cocoa Mug', 'Warm', 1),
            P('oven', '🧑‍🍳', 'Mini Oven', 'Ding!', 2),
            P('macaron', '🍬', 'Galaxy Macaron', 'Pastel', 2),
        ],
    },

    // ─── Star Studios (hidden playsets, no map pin) ──────────────────────────
    {
        key: 'sound_music_studio',
        name: 'Cosmic Sound & Music Studio',
        shortName: 'Music Studio',
        tag: 'AUDIO BOOTH',
        subtitle: 'DJ Lounge • Rainbow Turntables',
        blurb: 'Music booth, rainbow turntables, synth lounge and soundwave backdrop',
        status: 'Beat Dropping',
        district: 'studios',
        category: 'secret',
        emoji: '🎧',
        tone: 'grape',
        unlockCost: 180,
        image: 'sound_music_studio',
        ambience: ['🎵 BPM: 120', '🎚️ Mixer: LIVE'],
        hotspots: [
            H('turntable', 35, 50, '🎧', 'Rainbow Turntables', 'Wiki-wiki! Minni scratches a comet beat.'),
            H('synth', 68, 45, '🎹', 'Synth Lounge', 'Boop beep bloop. That\'s the alien hit single.'),
            H('mic', 50, 72, '🎤', 'Bubble Mic', 'La la LAAA! The soundwaves turn pink.'),
            H('speaker', 15, 65, '🔊', 'Star Speaker', 'BOOM. The planets wobble a little.'),
        ],
        actions: [
            A('drop', '🎚️', 'Drop Beat', 'Three… two… one… DROP! Confetti stars!'),
            A('sing', '🎤', 'Sing', 'Minni sings about soda bubbles. Catchy!'),
            A('record', '⏺️', 'Record', 'Track saved: "Bubble Planet Bop".'),
        ],
        routine: {
            title: 'Studio Session Routine',
            subtitle: 'Record a cosmic hit!',
            badge: 'Gold Record Badge 💿',
            tasks: [T('beat', 'Beat built'), T('vocals', 'Vocals recorded'), T('release', 'Song released')],
        },
        props: [
            P('headphones', '🎧', 'Neon Headphones', 'DJ Gear', 2),
            P('keyboard', '🎹', 'Star Synth', 'Boop!', 3),
            P('mic', '🎤', 'Bubble Mic', 'Sing!', 1),
            P('speaker', '🔊', 'Boom Speaker', 'Loud', 2),
            P('record', '💿', 'Gold Record', 'Hit Single', 4),
            P('guitar', '🎸', 'Comet Guitar', 'Rock!', 2),
        ],
    },
    {
        key: 'emote_animation_studio',
        name: 'Emote & Animation Studio',
        shortName: 'Emote Studio',
        tag: 'RECORDING STAGE',
        subtitle: 'Visualizer Floor • Director Cam',
        blurb: 'Recording stage with glowing visualizer floor, director cam and emoji reaction bubbles',
        status: 'Cameras Rolling',
        district: 'studios',
        category: 'secret',
        emoji: '🎬',
        tone: 'magenta',
        unlockCost: 180,
        image: 'emote_animation_studio',
        ambience: ['🎬 Take: 7', '💡 Stage Lights: ON'],
        hotspots: [
            H('stage', 50, 60, '🌟', 'Glow Stage', 'Minni strikes a pose! The floor lights up pink.'),
            H('camera', 20, 40, '🎥', 'Director Cam', 'Aaand… ACTION! Big smile!'),
            H('emojis', 75, 30, '😄', 'Reaction Bubbles', 'Happy! Surprised! Sleepy! So many faces!'),
            H('props', 80, 72, '🎭', 'Prop Chest', 'A rubber chicken? Perfect for take eight.'),
        ],
        actions: [
            A('dance', '💃', 'Dance', 'Spin, jump, jazz hands! Nailed it.'),
            A('emote', '😂', 'Emote', 'Giggle emote unlocked. Very contagious.'),
            A('replay', '⏪', 'Replay', 'Watching the take back… that jump was HUGE.'),
        ],
        routine: {
            title: 'Director Routine',
            subtitle: 'Shoot a mini movie!',
            badge: 'Clapperboard Badge 🎬',
            tasks: [T('lights', 'Lights set'), T('take', 'Best take recorded'), T('credits', 'Credits rolled')],
        },
        props: [
            P('camera', '🎥', 'Director Cam', 'Rolling', 3),
            P('clapper', '🎬', 'Clapperboard', 'Take 1', 1),
            P('spotlight', '💡', 'Spotlight', 'Bright', 2),
            P('mask', '🎭', 'Drama Masks', 'Props', 1),
            P('popcorn', '🍿', 'Popcorn', 'Snack', 1),
            P('trophy', '🏆', 'Star Award', 'Best Emote', 4),
        ],
    },
    {
        key: 'vip_wardrobe_studio',
        name: 'VIP Wardrobe Studio',
        shortName: 'Wardrobe',
        tag: 'DRESSING ROOM',
        subtitle: 'Rotating Racks • Vanity Mirror',
        blurb: 'Circular rotating garment racks, illuminated vanity, wings and accessories',
        status: 'New Arrivals',
        district: 'studios',
        category: 'secret',
        emoji: '👗',
        tone: 'pink',
        unlockCost: 160,
        image: 'vip_wardrobe_studio',
        ambience: ['✨ Racks: ROTATING', '🪞 Mirror: LIT'],
        hotspots: [
            H('racks', 30, 45, '👗', 'Garment Racks', 'A cape, a tutu, a space suit… all at once?'),
            H('mirror', 70, 40, '🪞', 'Vanity Mirror', 'Mirror mirror, who\'s the sparkliest? You!'),
            H('wings', 78, 72, '🦋', 'Wing Wall', 'Butterfly wings! Minni flutters around.'),
            H('shoes', 22, 76, '👟', 'Shoe Tower', 'Moon boots, bouncy and glowy.'),
        ],
        actions: [
            A('tryon', '👚', 'Try On', 'Twirl! This outfit is out of this world.'),
            A('spin', '🔄', 'Spin Rack', 'Whirr… the rack spins to a glitter hoodie.'),
            A('photo', '📸', 'Photo', 'Say cheese! Snap! Fabulous.'),
        ],
        routine: {
            title: 'Fashion Show Routine',
            subtitle: 'Put together the perfect look!',
            badge: 'Runway Star Badge 💖',
            tasks: [T('outfit', 'Outfit picked'), T('shoes', 'Moon boots laced'), T('walk', 'Runway walked')],
        },
        props: [
            P('rack', '👗', 'Mini Rack', 'Rotating', 3),
            P('mirror', '🪞', 'Vanity Mirror', 'Lit', 2),
            P('wings', '🦋', 'Butterfly Wings', 'Flutter', 2),
            P('boots', '👢', 'Moon Boots', 'Bouncy', 1),
            P('crown', '👑', 'Star Crown', 'Royal', 4),
            P('bag', '👜', 'Nebula Bag', 'Chic', 1),
        ],
    },
    {
        key: 'secret_star_treehouse',
        name: 'Secret Star Treehouse',
        shortName: 'Treehouse',
        tag: 'HIDDEN PLAYSET',
        subtitle: 'Glow Tree • Magic Observatory',
        blurb: 'Secret hollow glow-tree observatory, stargazing pod, crystal chest and hammock',
        status: 'Shh… Secret',
        district: 'studios',
        category: 'secret',
        emoji: '🌳',
        tone: 'mint',
        unlockCost: 250,
        image: 'secret_star_treehouse',
        ambience: ['🔮 Crystals: HUMMING', '🌙 Sky: CLEAR'],
        hotspots: [
            H('pod', 60, 30, '🔭', 'Stargazing Pod', 'The pod opens up… a thousand stars say hi.'),
            H('chest', 30, 55, '💎', 'Crystal Chest', 'The chest hums. Inside: a glowing star seed!'),
            H('hammock', 70, 70, '🪢', 'Hammock', 'Swaying gently. Minni yawns a happy yawn.'),
            H('ladder', 20, 78, '🪜', 'Glow Ladder', 'Up, up, up the shining tree!'),
        ],
        actions: [
            A('wish', '🌠', 'Make a Wish', 'A shooting star! Minni wished for more cookies.'),
            A('hide', '🙈', 'Hide', 'Shh… nobody can find Minni in the hollow.'),
            A('glow', '💡', 'Glow', 'The whole tree lights up like a lantern!'),
        ],
        routine: {
            title: 'Secret Keeper Routine',
            subtitle: 'Unlock the treehouse mysteries!',
            badge: 'Crystal Key Badge 🔑',
            tasks: [T('climb', 'Tree climbed'), T('chest', 'Crystal chest opened'), T('wish', 'Wish made')],
        },
        props: [
            P('crystal', '💎', 'Glow Crystal', 'Humming', 3),
            P('lantern', '🏮', 'Star Lantern', 'Cosy', 1),
            P('hammock', '🪢', 'Mini Hammock', 'Swaying', 2),
            P('owl', '🦉', 'Night Owl', 'Hoot', 2),
            P('telescope', '🔭', 'Pod Telescope', 'Stargaze', 3),
            P('key', '🔑', 'Crystal Key', 'Secret', 4),
        ],
    },
];

export const PLAYSETS_BY_KEY: Record<string, PlaysetDef> = Object.fromEntries(PLAYSETS.map((p) => [p.key, p]));

export const DISTRICTS: DistrictDef[] = [
    {
        key: 'island',
        name: 'Starry Island City',
        sector: 'Orbit Sector 07',
        tagline: 'Tap any pin or building to enter!',
        map: 'island',
        pins: [
            { playsetKey: 'starlight_school_observatory', x: 18, y: 44 },
            { playsetKey: 'cozy_heart_hospital', x: 34, y: 30 },
            { playsetKey: 'cosmic_dome_stadium', x: 51, y: 20 },
            { playsetKey: 'mega_shopping_mall', x: 68, y: 34 },
            { playsetKey: 'star_soda_arcade', x: 85, y: 50 },
            { playsetKey: 'sweet_lilac_bungalow', x: 34, y: 62 },
            { playsetKey: 'empire_builder_plot', x: 66, y: 66 },
            { playsetKey: 'rainbow_playground', x: 50, y: 82 },
        ],
    },
    {
        key: 'transit',
        name: 'Transit & Market Plaza',
        sector: 'Orbit Sector 02',
        tagline: 'Tap any station or shop to enter!',
        map: 'transit',
        pins: [
            { playsetKey: 'cosmic_bus_terminal', x: 26, y: 36 },
            { playsetKey: 'star_gas_car_wash', x: 47, y: 22 },
            { playsetKey: 'rainbow_railway_station', x: 74, y: 34 },
            { playsetKey: 'fresh_farmers_market', x: 58, y: 58 },
            { playsetKey: 'sweet_moon_bakery', x: 36, y: 66 },
        ],
    },
    {
        key: 'studios',
        name: 'Star Studios',
        sector: 'Hidden Sector ✦',
        tagline: 'Secret bubbles — tap one to peek inside!',
        map: null,
        pins: [
            { playsetKey: 'sound_music_studio', x: 22, y: 34 },
            { playsetKey: 'emote_animation_studio', x: 66, y: 26 },
            { playsetKey: 'vip_wardrobe_studio', x: 36, y: 72 },
            { playsetKey: 'secret_star_treehouse', x: 76, y: 68 },
        ],
    },
];

export const CATEGORY_FILTERS: { key: 'all' | import('../types').ZoneCategory; label: string; emoji: string }[] = [
    { key: 'all', label: 'All Places', emoji: '🌈' },
    { key: 'community', label: 'Community & Learn', emoji: '🏫' },
    { key: 'shopping', label: 'Shopping & Fun', emoji: '🛍️' },
    { key: 'homes', label: 'Homes & Build', emoji: '🏡' },
    { key: 'travel', label: 'Travel', emoji: '🚌' },
    { key: 'food', label: 'Food & Markets', emoji: '🍎' },
    { key: 'service', label: 'Service & Fuel', emoji: '🔧' },
    { key: 'secret', label: 'Star Studios', emoji: '✨' },
];
