import type { DistrictDef, PlaysetDef } from '../types';

// Every playset in the Cosmic Bubble asset stack, arranged into three districts that
// match the Stitch world-map screens: "Starry Island City" (the island map),
// "Transit & Market Plaza" (the transit map) and "Star Studios" (the four hidden
// studio/secret playsets that have no map pin and float as bubbles instead).
//
// Hotspot x/y are percentages of the scene image (1200×896, 4:3).

const H = (id: string, x: number, y: number, emoji: string, label: string, reaction: string) => ({ id, x, y, emoji, label, reaction });
const A = (id: string, emoji: string, label: string, reaction: string) => ({ id, emoji, label, reaction });
const T = (id: string, label: string) => ({ id, label });
const P = (id: string, emoji: string, name: string, sub: string, rarity: 1 | 2 | 3 | 4) => ({ id, emoji, name, sub, rarity });

export const PLAYSETS: PlaysetDef[] = [
    // ─── Starry Island City ──────────────────────────────────────────────────
    {
        key: 'sweet_lilac_bungalow',
        name: 'Sweet Lilac Bungalow',
        shortName: 'Bungalow',
        tag: 'COZY DUPLEX',
        subtitle: 'Cloud Plot 04 • Mezzanine & Patio',
        blurb: 'Cosy bedrooms, kitchen, backyard & flowers',
        status: 'Duplex #4 & #5',
        district: 'island',
        category: 'homes',
        emoji: '🏡',
        tone: 'pink',
        unlockCost: 0,
        image: 'sweet_lilac_bungalow',
        ambience: ['💡 Bedtime Lamp: ON', '☕ Kettle: STEAMING'],
        hotspots: [
            H('loft', 52, 26, '🌙', 'Star Loft', 'Minni is cozy in pajamas! Tap the sofa to curl up.'),
            H('lounge', 26, 62, '🛋️', 'Marshmallow Lounge', 'The sofa is soooo squishy. Five more minutes!'),
            H('kitchen', 75, 60, '🍳', 'Pastel Kitchen', 'Star toast is popping! Who wants jam?'),
            H('garden', 80, 80, '🌸', 'Cloud Garden', 'The candy fern says hello. It smiles back!'),
        ],
        actions: [
            A('snooze', '💤', 'Snooze', 'Zzz… Minni dreams of bubble planets.'),
            A('cocoa', '☕', 'Star Cocoa', 'Mmm, warm cocoa with marshmallow moons!'),
            A('cushions', '🧹', 'Cushions', 'Cushions fluffed! The lounge is ready for guests.'),
        ],
        routine: {
            title: 'Bedtime Star Routine',
            subtitle: 'Tuck Minni into the Cloud Bed!',
            badge: 'Sleepy Star Badge 🌙',
            tasks: [T('duvet', 'Cloud duvet fluffed'), T('nightlight', 'Starlight nightlight lit'), T('story', 'Bedtime story read')],
        },
        props: [
            P('cloud_bed', '🛏️', 'Star Cloud Bed', 'Fluffy Sleep', 4),
            P('vanity', '🪞', 'Lilac Vanity Desk', 'Studio Glow', 3),
            P('sofa', '🛋️', 'Marshmallow Sofa', 'Squishy Pink', 2),
            P('moon_lamp', '🌙', 'Moon Table Lamp', 'Warm Gold', 1),
            P('toaster', '🍞', 'Starlight Toaster', 'Pastel Toast', 1),
            P('fern', '🪴', 'Potted Candy Fern', 'Botanical', 1),
        ],
    },
    {
        key: 'starlight_school_observatory',
        name: 'Starlight School & Observatory',
        shortName: 'School',
        tag: 'SCIENCE LAB',
        subtitle: 'Orbit Sector 07 • Dome Telescope',
        blurb: 'Cosmic science & star gazing telescope',
        status: '4 Friends inside',
        district: 'island',
        category: 'community',
        emoji: '🔭',
        tone: 'violet',
        unlockCost: 0,
        image: 'starlight_school_observatory',
        ambience: ['🔭 Telescope: ALIGNED', '🧪 Potions: BUBBLING'],
        hotspots: [
            H('telescope', 70, 22, '🔭', 'Brass Telescope', 'I can see a bubble planet! It has rings made of candy!'),
            H('lab', 30, 40, '🧪', 'Potion Lab', 'Careful… the purple potion fizzes when you giggle.'),
            H('desks', 45, 70, '📚', 'Student Desks', 'Today\'s lesson: how many stars fit in a soda can?'),
            H('globe', 78, 66, '🌍', 'Celestial Globe', 'Spin the globe! Where should we fly next?'),
        ],
        actions: [
            A('stargaze', '✨', 'Stargaze', 'Three shooting stars! Make a wish, quick!'),
            A('experiment', '🧪', 'Experiment', 'POP! The potion turned into rainbow bubbles.'),
            A('bell', '🔔', 'Ring Bell', 'Ding ding! Recess on the moon deck!'),
        ],
        routine: {
            title: 'Star Science Routine',
            subtitle: 'Finish today\'s cosmic lesson!',
            badge: 'Little Astronomer Badge 🔭',
            tasks: [T('chart', 'Star chart drawn'), T('potion', 'Rainbow potion mixed'), T('planet', 'New planet named')],
        },
        props: [
            P('telescope', '🔭', 'Mini Telescope', 'Brass Dome', 3),
            P('globe', '🪐', 'Celestial Globe', 'Spins!', 2),
            P('beaker', '🧪', 'Fizzy Beaker', 'Potion Lab', 1),
            P('books', '📚', 'Star Books', 'Reading Nook', 1),
            P('rocket_model', '🚀', 'Rocket Model', 'Science Fair', 2),
            P('chalkboard', '🧮', 'Moon Chalkboard', 'Lesson Time', 1),
        ],
    },
    {
        key: 'cozy_heart_hospital',
        name: 'Cozy Heart Hospital',
        shortName: 'Hospital',
        tag: 'HEALTH CENTER',
        subtitle: 'Pediatric Clinic • Open 24/7',
        blurb: 'Emergency nursery, X-ray & pet care',
        status: 'Open 24/7',
        district: 'island',
        category: 'community',
        emoji: '🏥',
        tone: 'pink',
        unlockCost: 120,
        image: 'cozy_heart_hospital',
        ambience: ['❤️ Heart Monitor: BEEP', '🍼 Nursery: QUIET'],
        hotspots: [
            H('checkup', 30, 45, '🩺', 'Checkup Bed', 'Say ahh! Everything looks sparkly-healthy.'),
            H('cradle', 68, 36, '🌙', 'Moon Cradle', 'Shh… the baby stars are sleeping.'),
            H('xray', 78, 70, '🦴', 'Alien X-Ray', 'Whoa, three hearts! That\'s totally normal for aliens.'),
            H('pharmacy', 22, 74, '💊', 'Candy Pharmacy', 'One star vitamin a day keeps the grumps away.'),
        ],
        actions: [
            A('bandage', '🩹', 'Bandage', 'All patched up with a glitter bandage!'),
            A('checkup', '🩺', 'Checkup', 'Heartbeat sounds like a tiny drum. Perfect!'),
            A('lullaby', '🎵', 'Lullaby', 'Twinkle twinkle… the nursery yawns.'),
        ],
        routine: {
            title: 'Doctor Star Routine',
            subtitle: 'Help every patient feel better!',
            badge: 'Kind Heart Badge ❤️',
            tasks: [T('temp', 'Temperature taken'), T('bandage', 'Glitter bandage applied'), T('lollipop', 'Brave lollipop given')],
        },
        props: [
            P('bed', '🛏️', 'Checkup Bed', 'Soft Pink', 2),
            P('cradle', '🌙', 'Moon Cradle', 'Nursery', 3),
            P('teddy', '🧸', 'Get-Well Teddy', 'Cuddly', 1),
            P('kit', '🩺', 'Doctor Kit', 'Stethoscope', 1),
            P('wheelchair', '🦽', 'Star Wheelchair', 'Zoomy', 2),
            P('balloon', '🎈', 'Cheer Balloon', 'Heart Shaped', 1),
        ],
    },
    {
        key: 'cosmic_dome_stadium',
        name: 'Cosmic Dome Stadium',
        shortName: 'Stadium',
        tag: 'SPORTS',
        subtitle: 'Roller Derby Arena • Zero-G Field',
        blurb: 'Zero-G soccer & neon roller skate ring',
        status: 'Roller Derby Live',
        district: 'island',
        category: 'community',
        emoji: '🏟️',
        tone: 'mint',
        unlockCost: 150,
        image: 'cosmic_dome_stadium',
        ambience: ['🛼 Derby: LIVE', '📣 Crowd: LOUD'],
        hotspots: [
            H('track', 40, 60, '🛼', 'Rainbow Track', 'Wheee! Minni skates a full loop in zero gravity!'),
            H('goal', 75, 40, '⚽', 'Zero-G Goal', 'GOOOAL! The ball floated in slow motion.'),
            H('board', 50, 18, '🏆', 'Scoreboard', 'Home team: 3. Comets: 3. Cosmic tie!'),
            H('bleachers', 18, 40, '📣', 'Bleachers', 'The crowd does the wave… in space it takes a while.'),
        ],
        actions: [
            A('kick', '⚽', 'Kick Off', 'Boom! The ball bounces off the dome glass.'),
            A('skate', '🛼', 'Skate Lap', 'Zoom zoom! Fastest lap of the day.'),
            A('cheer', '📣', 'Cheer', 'GO MINNI GO! The bleachers glow pink.'),
        ],
        routine: {
            title: 'Champion Routine',
            subtitle: 'Warm up, play, celebrate!',
            badge: 'Gold Whistle Badge 🏅',
            tasks: [T('stretch', 'Space stretches done'), T('lap', 'Derby lap finished'), T('trophy', 'Trophy polished')],
        },
        props: [
            P('ball', '⚽', 'Bubble Ball', 'Zero-G', 1),
            P('trophy', '🏆', 'Star Trophy', 'Shiny', 3),
            P('skates', '🛼', 'Neon Skates', 'Speedy', 2),
            P('cone', '🔶', 'Training Cone', 'Practice', 1),
            P('flag', '🚩', 'Team Flag', 'Go Comets!', 1),
            P('whistle', '🎽', 'Coach Jersey', 'Number 7', 2),
        ],
    },
    {
        key: 'mega_shopping_mall',
        name: 'Mega Shopping Mall',
        shortName: 'Mall',
        tag: 'SHOPPING',
        subtitle: '3 Floors • Space Galleria',
        blurb: 'Fashion boutique, boba shop & food court',
        status: '3 Floors of Fashion',
        district: 'island',
        category: 'shopping',
        emoji: '🛍️',
        tone: 'violet',
        unlockCost: 150,
        image: 'mega_shopping_mall',
        ambience: ['🛗 Escalators: GLIDING', '🧋 Boba: SHAKING'],
        hotspots: [
            H('boutique', 25, 40, '👗', 'Star Boutique', 'Ooh, a sparkle cape! It matches my helmet.'),
            H('diner', 70, 30, '🍔', 'Starlite Diner', 'Milkshake with a moon on top, please!'),
            H('boba', 55, 62, '🧋', 'Boba Bar', 'Galaxy boba! The pearls glow in the dark.'),
            H('cosmetics', 78, 72, '💄', 'Cosmetics Bar', 'Glitter cheeks activated. Fabulous!'),
        ],
        actions: [
            A('shop', '🛍️', 'Window Shop', 'So many shiny things! Just looking… for now.'),
            A('escalator', '🛗', 'Ride Up', 'Wheee, the escalator floats to floor three!'),
            A('snack', '🍟', 'Snack Time', 'Star fries with rainbow ketchup. Yum!'),
        ],
        routine: {
            title: 'Shopping Spree Routine',
            subtitle: 'Visit every floor of the galleria!',
            badge: 'Style Star Badge 👑',
            tasks: [T('floor1', 'Boutique visited'), T('floor2', 'Boba tasted'), T('floor3', 'Food court explored')],
        },
        props: [
            P('mannequin', '👗', 'Sparkle Dress', 'Boutique', 3),
            P('boba', '🧋', 'Galaxy Boba', 'Glow Pearls', 1),
            P('bag', '🛍️', 'Shopping Bag', 'Full!', 1),
            P('milkshake', '🥤', 'Moon Milkshake', 'Diner', 1),
            P('mirror', '🪞', 'Selfie Mirror', 'Cosmetics', 2),
            P('gift', '🎁', 'Mystery Gift', 'Wrapped', 2),
        ],
    },
    {
        key: 'star_soda_arcade',
        name: 'Star Soda Arcade',
        shortName: 'Arcade',
        tag: 'MINI GAMES',
        subtitle: 'Game Zone • Ticket Shop',
        blurb: 'Claw machines, dance pad & ticket shop',
        status: 'High Scores',
        district: 'island',
        category: 'shopping',
        emoji: '🕹️',
        tone: 'aqua',
        unlockCost: 0,
        image: 'star_soda_arcade',
        ambience: ['🕹️ Machines: ON', '🎟️ Tickets: 9,420'],
        hotspots: [
            H('claw', 22, 40, '🧸', 'Claw Machine', 'Almost… almost… GOT IT! A jelly plushie!'),
            H('dance', 50, 68, '💃', 'Dance Pad', 'Left, right, spin! Perfect combo!'),
            H('pinball', 75, 40, '🎯', 'Pinball', 'Ding ding ding! Multiball mode!'),
            H('prizes', 80, 74, '🎟️', 'Prize Counter', 'Enough tickets for the giant star plush!'),
        ],
        actions: [
            A('play', '🎮', 'Play', 'New high score! The machine sings a little song.'),
            A('dance', '🕺', 'Dance', 'Disco lights on! Everybody wiggle!'),
            A('tickets', '🎟️', 'Cash Tickets', 'Tickets traded for a glow-in-the-dark yoyo.'),
        ],
        routine: {
            title: 'Arcade Champ Routine',
            subtitle: 'Beat every machine once!',
            badge: 'Pixel Star Badge 🎮',
            tasks: [T('claw', 'Claw prize won'), T('dance', 'Dance combo landed'), T('pinball', 'Pinball jackpot hit')],
        },
        props: [
            P('claw', '🧸', 'Claw Plushie', 'Jelly Soft', 2),
            P('cabinet', '🕹️', 'Retro Cabinet', 'Neon', 3),
            P('hockey', '🏒', 'Air Hockey', 'Slidey', 2),
            P('token', '🪙', 'Star Token', 'Shiny', 1),
            P('soda', '🥤', 'Star Soda', 'Fizzy', 1),
            P('yoyo', '🪀', 'Glow Yoyo', 'Prize', 1),
        ],
    },
    {
        key: 'rainbow_playground',
        name: 'Rainbow Playground',
        shortName: 'Playground',
        tag: 'OUTDOOR PARK',
        subtitle: 'Cloud Island • Family Chill',
        blurb: 'Big slides, seesaws, sandbox & ice cream van',
        status: 'Family Chill',
        district: 'island',
        category: 'community',
        emoji: '🎠',
        tone: 'gold',
        unlockCost: 0,
        image: 'rainbow_playground',
        ambience: ['☀️ Weather: SUNNY', '🍦 Ice Cream: FRESH'],
        hotspots: [
            H('slide', 30, 40, '🌈', 'Rainbow Slide', 'WHEEEEE! Down the rainbow and into the clouds!'),
            H('carousel', 68, 36, '🎠', 'Star Carousel', 'Round and round on a flying star horse!'),
            H('sandbox', 50, 74, '🏖️', 'Sandbox', 'Building a moon castle with a bubble moat.'),
            H('trampoline', 80, 70, '🍄', 'Mushroom Trampoline', 'Boing! Boing! Minni touched a cloud!'),
        ],
        actions: [
            A('swing', '🎢', 'Swing', 'Higher! Higher! Minni can see the whole island!'),
            A('icecream', '🍦', 'Ice Cream', 'Triple scoop: nebula, comet crunch and bubblegum.'),
            A('picnic', '🧺', 'Picnic', 'Sandwiches shaped like stars. Naturally.'),
        ],
        routine: {
            title: 'Sunny Day Routine',
            subtitle: 'Play, snack and rest!',
            badge: 'Sunshine Badge ☀️',
            tasks: [T('slide', 'Slide ridden 3 times'), T('castle', 'Moon castle built'), T('rest', 'Cloud nap taken')],
        },
        props: [
            P('slide', '🛝', 'Mini Slide', 'Rainbow', 3),
            P('seesaw', '⚖️', 'Seesaw', 'Up & Down', 2),
            P('bucket', '🪣', 'Sand Bucket', 'Sandbox', 1),
            P('kite', '🪁', 'Star Kite', 'Windy', 1),
            P('icecream', '🍦', 'Ice Cream', 'Triple Scoop', 1),
            P('ball', '🏐', 'Beach Ball', 'Bouncy', 1),
        ],
    },
    {
        key: 'empire_builder_plot',
        name: 'Empire Builder Plot',
        shortName: 'Build Lot',
        tag: 'SPECIAL LOT',
        subtitle: 'Plot #01 • Creative Sandbox',
        blurb: 'Custom villa, star pool & garden',
        status: 'Ready to Build',
        district: 'island',
        category: 'homes',
        emoji: '🏰',
        tone: 'gold',
        unlockCost: 200,
        image: 'empire_builder_plot',
        ambience: ['🏗️ Crane: READY', '📐 Blueprints: 3'],
        hotspots: [
            H('crane', 70, 28, '🏗️', 'Pastel Crane', 'Lifting a marshmallow wall into place. Steady…'),
            H('table', 28, 48, '📐', 'Drafting Table', 'Blueprint idea: a slide from the bedroom to the pool!'),
            H('pool', 55, 72, '🏊', 'Star Pool', 'Splash! The water is fizzy like soda.'),
            H('garden', 20, 76, '🌷', 'Garden Bed', 'Planting glow tulips. They light up at night!'),
        ],
        actions: [
            A('build', '🔨', 'Build', 'Wall up! The villa grows another storey.'),
            A('paint', '🎨', 'Paint', 'Bubblegum pink with cyan trim. Gorgeous!'),
            A('plant', '🌱', 'Plant', 'Star seeds planted. Water with sparkle juice.'),
        ],
        routine: {
            title: 'Master Builder Routine',
            subtitle: 'Raise the star villa!',
            badge: 'Hard Hat Badge 🏗️',
            tasks: [T('blueprint', 'Blueprint drawn'), T('walls', 'Walls stacked'), T('roof', 'Star roof placed')],
        },
        props: [
            P('crane', '🏗️', 'Mini Crane', 'Lifts!', 4),
            P('bricks', '🧱', 'Candy Bricks', 'Stackable', 1),
            P('pool', '🏊', 'Star Pool', 'Splashy', 3),
            P('fence', '🪵', 'Pastel Fence', 'Garden', 1),
            P('tulip', '🌷', 'Glow Tulip', 'Botanical', 1),
            P('roof', '🏠', 'Star Roof', 'Finishing', 2),
        ],
    },

    // ─── Transit & Market Plaza ──────────────────────────────────────────────
    {
        key: 'cosmic_bus_terminal',
        name: 'Cosmic Bus Terminal',
        shortName: 'Bus Depot',
        tag: 'TRANSIT HUB',
        subtitle: 'Boarding Bay 3 • Waiting Lounge',
        blurb: 'Board double-decker star buses, luggage lockers & ticket punch',
        status: '3 Buses Arriving',
        district: 'transit',
        category: 'travel',
        emoji: '🚌',
        tone: 'aqua',
        unlockCost: 0,
        image: 'cosmic_bus_terminal',
        ambience: ['🚌 Next Bus: 2 MIN', '🎫 Gate: OPEN'],
        hotspots: [
            H('bus', 35, 55, '🚌', 'Star Bus', 'Top deck, front seat! Best view of the nebula.'),
            H('board', 60, 22, '🛰️', 'Departure Board', 'Next stop: Bakery Moon, then Rainbow Station.'),
            H('lockers', 78, 50, '🧳', 'Luggage Lockers', 'Locker 12 has a snack stash. Don\'t tell.'),
            H('vending', 82, 76, '🥤', 'Vending Machine', 'Galaxy fizz, ka-chunk! It glows purple.'),
        ],
        actions: [
            A('ticket', '🎫', 'Punch Ticket', 'Click! Ticket punched with a star shape.'),
            A('board', '🚌', 'Board Bus', 'All aboard! The doors fold shut with a hiss.'),
            A('wait', '🪑', 'Lounge', 'Galaxy pillows are the comfiest waiting spot.'),
        ],
        routine: {
            title: 'Traveller Routine',
            subtitle: 'Catch the star bus on time!',
            badge: 'Star Commuter Badge 🎫',
            tasks: [T('ticket', 'Ticket bought'), T('locker', 'Bag stored'), T('bus', 'Bus boarded')],
        },
        props: [
            P('bus', '🚌', 'Toy Star Bus', 'Double Decker', 4),
            P('suitcase', '🧳', 'Galaxy Suitcase', 'Packed', 1),
            P('bench', '🪑', 'Lounge Seat', 'Plush', 1),
            P('sign', '🪧', 'Route Sign', 'Bay 3', 1),
            P('drink', '🥤', 'Galaxy Fizz', 'Vending', 1),
            P('clock', '🕰️', 'Depot Clock', 'Tick Tock', 2),
        ],
    },
    {
        key: 'rainbow_railway_station',
        name: 'Grand Rainbow Railway Station',
        shortName: 'Railway',
        tag: 'EXPRESS LINE',
        subtitle: 'Platform 1 • Bubble Train',
        blurb: 'Ride the high-speed maglev bubble train across cosmic nebulae',
        status: 'Bubble Train on Platform',
        district: 'transit',
        category: 'travel',
        emoji: '🚂',
        tone: 'violet',
        unlockCost: 120,
        image: 'rainbow_railway_station',
        ambience: ['🚆 Train: BOARDING', '🕰️ Clock Tower: 3:00'],
        hotspots: [
            H('train', 62, 42, '🚆', 'Bubble Train', 'Whoosh! The train floats above the rainbow rails.'),
            H('clock', 30, 20, '🕰️', 'Clock Tower', 'Bong! Bong! Three o\'clock — cookie time.'),
            H('platform', 40, 66, '🛤️', 'Platform 1', 'Mind the gap… it\'s full of stars!'),
            H('luggage', 15, 60, '🧳', 'Luggage Racks', 'Whose suitcase is glowing? Ooh, mine!'),
        ],
        actions: [
            A('whistle', '📯', 'Whistle', 'Toot toot! Departing for Nebula Nine.'),
            A('ride', '🚆', 'Ride', 'The windows show comets zooming past. Amazing!'),
            A('snack', '🍪', 'Snack Cart', 'Rainbow cookie from the cart. Crunch!'),
        ],
        routine: {
            title: 'Conductor Routine',
            subtitle: 'Get the bubble train rolling!',
            badge: 'Conductor Cap Badge 🎩',
            tasks: [T('tickets', 'Tickets checked'), T('whistle', 'Whistle blown'), T('depart', 'Train departed')],
        },
        props: [
            P('train', '🚂', 'Toy Bubble Train', 'Maglev', 4),
            P('signal', '🚦', 'Rail Signal', 'Green!', 1),
            P('cart', '🛒', 'Snack Cart', 'Cookies', 2),
            P('bench', '🪑', 'Platform Bench', 'Waiting', 1),
            P('map', '🗺️', 'Route Map', 'All Lines', 1),
            P('lantern', '🏮', 'Station Lantern', 'Glowing', 2),
        ],
    },
    {
        key: 'star_gas_car_wash',
        name: 'Star Gas, EV & Car Wash',
        shortName: 'Gas & Wash',
        tag: 'PIT STOP',
        subtitle: 'Wash Bay • EV Charging Hub',
        blurb: 'Neon fuel pumps, solar plugs & bubbly car wash sponge tunnel',
        status: 'Wash Bay Open',
        district: 'transit',
        category: 'service',
        emoji: '⛽',
        tone: 'teal',
        unlockCost: 100,
        image: 'star_gas_car_wash',
        ambience: ['🫧 Foam: MAXIMUM', '⚡ Charger: 80%'],
        hotspots: [
            H('pump', 30, 45, '⛽', 'Neon Pump', 'Fill her up with star soda fuel!'),
            H('tunnel', 68, 40, '🫧', 'Foam Tunnel', 'Bubbles everywhere! The car giggles.'),
            H('charger', 22, 74, '⚡', 'EV Charger', 'Zap zap! Charged by sunshine.'),
            H('garage', 78, 74, '🔧', 'Pit-Stop Garage', 'New tyres, extra bouncy.'),
        ],
        actions: [
            A('wash', '🧽', 'Wash', 'Scrub-a-dub! Sparkling clean.'),
            A('fuel', '⛽', 'Fuel Up', 'Glug glug glug… full tank of fizz!'),
            A('honk', '📣', 'Honk', 'Beep beep! The car sings back.'),
        ],
        routine: {
            title: 'Pit Crew Routine',
            subtitle: 'Get the car race-ready!',
            badge: 'Speedy Sponge Badge 🧽',
            tasks: [T('fuel', 'Tank filled'), T('wash', 'Foam wash done'), T('shine', 'Windows polished')],
        },
        props: [
            P('car', '🚗', 'Pastel Car', 'Vroom', 3),
            P('sponge', '🧽', 'Giant Sponge', 'Bubbly', 1),
            P('pump', '⛽', 'Mini Pump', 'Neon', 2),
            P('tyre', '🛞', 'Bouncy Tyre', 'Garage', 1),
            P('cone', '🚧', 'Wash Cone', 'Careful', 1),
            P('scooter', '🛵', 'Pastel Moped', 'Delivery', 2),
        ],
    },
    {
        key: 'fresh_farmers_market',
        name: 'Starlight Fresh Farmers Market',
        shortName: 'Market',
        tag: 'ORGANIC FARM',
        subtitle: 'Candy-Striped Stalls • Juice Stand',
        blurb: 'Crisp cosmic carrots, glowing stardust berries, scales & cashier!',
        status: 'Daily Harvest',
        district: 'transit',
        category: 'food',
        emoji: '🥕',
        tone: 'mint',
        unlockCost: 100,
        image: 'fresh_farmers_market',
        ambience: ['🍓 Berries: GLOWING', '⚖️ Scales: READY'],
        hotspots: [
            H('stall', 35, 45, '🍎', 'Fruit Stall', 'Star fruit! It actually twinkles.'),
            H('scales', 62, 50, '⚖️', 'Produce Scales', 'Three glow-berries weigh… one moonbeam.'),
            H('juice', 78, 30, '🧃', 'Juice Stand', 'Fresh nebula juice, extra sparkly!'),
            H('crates', 25, 74, '📦', 'Wooden Crates', 'Cosmic carrots, still warm from the sun.'),
        ],
        actions: [
            A('shop', '🧺', 'Fill Basket', 'Basket full of rainbow veggies!'),
            A('taste', '🍓', 'Taste', 'Mmm! Stardust berries pop like fizz.'),
            A('pay', '🪙', 'Pay', 'Ka-ching! Thank you, come again!'),
        ],
        routine: {
            title: 'Market Day Routine',
            subtitle: 'Shop the whole market!',
            badge: 'Fresh Picker Badge 🥕',
            tasks: [T('fruit', 'Star fruit picked'), T('weigh', 'Veggies weighed'), T('juice', 'Juice tasted')],
        },
        props: [
            P('basket', '🧺', 'Market Basket', 'Woven', 1),
            P('carrot', '🥕', 'Cosmic Carrot', 'Crunchy', 1),
            P('berries', '🍓', 'Glow Berries', 'Sparkly', 1),
            P('scales', '⚖️', 'Brass Scales', 'Weigh It', 2),
            P('juice', '🧃', 'Nebula Juice', 'Fresh', 1),
            P('stall', '🏪', 'Mini Stall', 'Striped', 3),
        ],
    },
    {
        key: 'sweet_moon_bakery',
        name: 'Sweet Moon Bakery & Café',
        shortName: 'Bakery',
        tag: 'FRESHLY BAKED',
        subtitle: 'Star Café • Oven Warm',
        blurb: 'Star bagels, rainbow croissants, cinnamon rolls & hot cocoa tap',
        status: 'Oven Warm',
        district: 'transit',
        category: 'food',
        emoji: '🥐',
        tone: 'gold',
        unlockCost: 0,
        image: 'sweet_moon_bakery',
        ambience: ['🔥 Oven: WARM', '☕ Espresso: FIZZING'],
        hotspots: [
            H('display', 35, 50, '🍩', 'Pastry Case', 'Star donuts with galaxy sprinkles. Take two!'),
            H('oven', 70, 40, '🔥', 'Moon Oven', 'Ding! The croissants are rainbow-golden.'),
            H('espresso', 78, 68, '☕', 'Soda Espresso', 'Fizzy cocoa with a marshmallow moon.'),
            H('booth', 20, 74, '🪑', 'Cosy Booth', 'Window seat! Watching comets go by.'),
        ],
        actions: [
            A('bake', '🧁', 'Bake', 'Whisk, pour, bake… star cupcakes!'),
            A('serve', '🍽️', 'Serve', 'Order up! Table three gets the macarons.'),
            A('taste', '🍩', 'Taste', 'Galaxy macaron. Crunchy, then fluffy. Perfect.'),
        ],
        routine: {
            title: 'Baker Routine',
            subtitle: 'Open the café for the morning rush!',
            badge: 'Sugar Star Badge 🧁',
            tasks: [T('dough', 'Dough kneaded'), T('bake', 'Donuts baked'), T('serve', 'First customer served')],
        },
        props: [
            P('donut', '🍩', 'Star Donut', 'Sprinkles', 1),
            P('croissant', '🥐', 'Rainbow Croissant', 'Flaky', 1),
            P('cake', '🎂', 'Moon Cake', 'Party!', 3),
            P('mug', '☕', 'Cocoa Mug', 'Warm', 1),
            P('oven', '🧑‍🍳', 'Mini Oven', 'Ding!', 2),
            P('macaron', '🍬', 'Galaxy Macaron', 'Pastel', 2),
        ],
    },

    // ─── Star Studios (hidden playsets, no map pin) ──────────────────────────
    {
        key: 'sound_music_studio',
        name: 'Cosmic Sound & Music Studio',
        shortName: 'Music Studio',
        tag: 'AUDIO BOOTH',
        subtitle: 'DJ Lounge • Rainbow Turntables',
        blurb: 'Music booth, rainbow turntables, synth lounge and soundwave backdrop',
        status: 'Beat Dropping',
        district: 'studios',
        category: 'secret',
        emoji: '🎧',
        tone: 'grape',
        unlockCost: 180,
        image: 'sound_music_studio',
        ambience: ['🎵 BPM: 120', '🎚️ Mixer: LIVE'],
        hotspots: [
            H('turntable', 35, 50, '🎧', 'Rainbow Turntables', 'Wiki-wiki! Minni scratches a comet beat.'),
            H('synth', 68, 45, '🎹', 'Synth Lounge', 'Boop beep bloop. That\'s the alien hit single.'),
            H('mic', 50, 72, '🎤', 'Bubble Mic', 'La la LAAA! The soundwaves turn pink.'),
            H('speaker', 15, 65, '🔊', 'Star Speaker', 'BOOM. The planets wobble a little.'),
        ],
        actions: [
            A('drop', '🎚️', 'Drop Beat', 'Three… two… one… DROP! Confetti stars!'),
            A('sing', '🎤', 'Sing', 'Minni sings about soda bubbles. Catchy!'),
            A('record', '⏺️', 'Record', 'Track saved: "Bubble Planet Bop".'),
        ],
        routine: {
            title: 'Studio Session Routine',
            subtitle: 'Record a cosmic hit!',
            badge: 'Gold Record Badge 💿',
            tasks: [T('beat', 'Beat built'), T('vocals', 'Vocals recorded'), T('release', 'Song released')],
        },
        props: [
            P('headphones', '🎧', 'Neon Headphones', 'DJ Gear', 2),
            P('keyboard', '🎹', 'Star Synth', 'Boop!', 3),
            P('mic', '🎤', 'Bubble Mic', 'Sing!', 1),
            P('speaker', '🔊', 'Boom Speaker', 'Loud', 2),
            P('record', '💿', 'Gold Record', 'Hit Single', 4),
            P('guitar', '🎸', 'Comet Guitar', 'Rock!', 2),
        ],
    },
    {
        key: 'emote_animation_studio',
        name: 'Emote & Animation Studio',
        shortName: 'Emote Studio',
        tag: 'RECORDING STAGE',
        subtitle: 'Visualizer Floor • Director Cam',
        blurb: 'Recording stage with glowing visualizer floor, director cam and emoji reaction bubbles',
        status: 'Cameras Rolling',
        district: 'studios',
        category: 'secret',
        emoji: '🎬',
        tone: 'magenta',
        unlockCost: 180,
        image: 'emote_animation_studio',
        ambience: ['🎬 Take: 7', '💡 Stage Lights: ON'],
        hotspots: [
            H('stage', 50, 60, '🌟', 'Glow Stage', 'Minni strikes a pose! The floor lights up pink.'),
            H('camera', 20, 40, '🎥', 'Director Cam', 'Aaand… ACTION! Big smile!'),
            H('emojis', 75, 30, '😄', 'Reaction Bubbles', 'Happy! Surprised! Sleepy! So many faces!'),
            H('props', 80, 72, '🎭', 'Prop Chest', 'A rubber chicken? Perfect for take eight.'),
        ],
        actions: [
            A('dance', '💃', 'Dance', 'Spin, jump, jazz hands! Nailed it.'),
            A('emote', '😂', 'Emote', 'Giggle emote unlocked. Very contagious.'),
            A('replay', '⏪', 'Replay', 'Watching the take back… that jump was HUGE.'),
        ],
        routine: {
            title: 'Director Routine',
            subtitle: 'Shoot a mini movie!',
            badge: 'Clapperboard Badge 🎬',
            tasks: [T('lights', 'Lights set'), T('take', 'Best take recorded'), T('credits', 'Credits rolled')],
        },
        props: [
            P('camera', '🎥', 'Director Cam', 'Rolling', 3),
            P('clapper', '🎬', 'Clapperboard', 'Take 1', 1),
            P('spotlight', '💡', 'Spotlight', 'Bright', 2),
            P('mask', '🎭', 'Drama Masks', 'Props', 1),
            P('popcorn', '🍿', 'Popcorn', 'Snack', 1),
            P('trophy', '🏆', 'Star Award', 'Best Emote', 4),
        ],
    },
    {
        key: 'vip_wardrobe_studio',
        name: 'VIP Wardrobe Studio',
        shortName: 'Wardrobe',
        tag: 'DRESSING ROOM',
        subtitle: 'Rotating Racks • Vanity Mirror',
        blurb: 'Circular rotating garment racks, illuminated vanity, wings and accessories',
        status: 'New Arrivals',
        district: 'studios',
        category: 'secret',
        emoji: '👗',
        tone: 'pink',
        unlockCost: 160,
        image: 'vip_wardrobe_studio',
        ambience: ['✨ Racks: ROTATING', '🪞 Mirror: LIT'],
        hotspots: [
            H('racks', 30, 45, '👗', 'Garment Racks', 'A cape, a tutu, a space suit… all at once?'),
            H('mirror', 70, 40, '🪞', 'Vanity Mirror', 'Mirror mirror, who\'s the sparkliest? You!'),
            H('wings', 78, 72, '🦋', 'Wing Wall', 'Butterfly wings! Minni flutters around.'),
            H('shoes', 22, 76, '👟', 'Shoe Tower', 'Moon boots, bouncy and glowy.'),
        ],
        actions: [
            A('tryon', '👚', 'Try On', 'Twirl! This outfit is out of this world.'),
            A('spin', '🔄', 'Spin Rack', 'Whirr… the rack spins to a glitter hoodie.'),
            A('photo', '📸', 'Photo', 'Say cheese! Snap! Fabulous.'),
        ],
        routine: {
            title: 'Fashion Show Routine',
            subtitle: 'Put together the perfect look!',
            badge: 'Runway Star Badge 💖',
            tasks: [T('outfit', 'Outfit picked'), T('shoes', 'Moon boots laced'), T('walk', 'Runway walked')],
        },
        props: [
            P('rack', '👗', 'Mini Rack', 'Rotating', 3),
            P('mirror', '🪞', 'Vanity Mirror', 'Lit', 2),
            P('wings', '🦋', 'Butterfly Wings', 'Flutter', 2),
            P('boots', '👢', 'Moon Boots', 'Bouncy', 1),
            P('crown', '👑', 'Star Crown', 'Royal', 4),
            P('bag', '👜', 'Nebula Bag', 'Chic', 1),
        ],
    },
    {
        key: 'secret_star_treehouse',
        name: 'Secret Star Treehouse',
        shortName: 'Treehouse',
        tag: 'HIDDEN PLAYSET',
        subtitle: 'Glow Tree • Magic Observatory',
        blurb: 'Secret hollow glow-tree observatory, stargazing pod, crystal chest and hammock',
        status: 'Shh… Secret',
        district: 'studios',
        category: 'secret',
        emoji: '🌳',
        tone: 'mint',
        unlockCost: 250,
        image: 'secret_star_treehouse',
        ambience: ['🔮 Crystals: HUMMING', '🌙 Sky: CLEAR'],
        hotspots: [
            H('pod', 60, 30, '🔭', 'Stargazing Pod', 'The pod opens up… a thousand stars say hi.'),
            H('chest', 30, 55, '💎', 'Crystal Chest', 'The chest hums. Inside: a glowing star seed!'),
            H('hammock', 70, 70, '🪢', 'Hammock', 'Swaying gently. Minni yawns a happy yawn.'),
            H('ladder', 20, 78, '🪜', 'Glow Ladder', 'Up, up, up the shining tree!'),
        ],
        actions: [
            A('wish', '🌠', 'Make a Wish', 'A shooting star! Minni wished for more cookies.'),
            A('hide', '🙈', 'Hide', 'Shh… nobody can find Minni in the hollow.'),
            A('glow', '💡', 'Glow', 'The whole tree lights up like a lantern!'),
        ],
        routine: {
            title: 'Secret Keeper Routine',
            subtitle: 'Unlock the treehouse mysteries!',
            badge: 'Crystal Key Badge 🔑',
            tasks: [T('climb', 'Tree climbed'), T('chest', 'Crystal chest opened'), T('wish', 'Wish made')],
        },
        props: [
            P('crystal', '💎', 'Glow Crystal', 'Humming', 3),
            P('lantern', '🏮', 'Star Lantern', 'Cosy', 1),
            P('hammock', '🪢', 'Mini Hammock', 'Swaying', 2),
            P('owl', '🦉', 'Night Owl', 'Hoot', 2),
            P('telescope', '🔭', 'Pod Telescope', 'Stargaze', 3),
            P('key', '🔑', 'Crystal Key', 'Secret', 4),
        ],
    },

    // ─── New Orbit Sectors (Galaxy — each a single-playset sector) ─────────────
    {
        key: 'sparkle_jungle',
        name: 'Sparkle Jungle',
        shortName: 'Sparkle Jungle',
        tag: 'MAGIC JUNGLE',
        subtitle: 'Candy River & Treehouse • Orbit Sector 02',
        blurb: 'A waterfall, lollipop flowers & a spiral treehouse slide',
        status: 'Koala & Bunny Playing',
        district: 'sparkle_jungle',
        category: 'community',
        emoji: '🌳',
        tone: 'mint',
        unlockCost: 180,
        image: 'sparkle_jungle',
        ambience: ['🌊 River: SPARKLING', '🐨 Koala: SLEEPY'],
        hotspots: [
            H('river', 45, 46, '🌊', 'Sparkle River', 'Splish splash! The river glitters all the way to the pond.'),
            H('treehouse', 74, 34, '🛝', 'Treehouse Slide', 'Wheee! Down the spiral slide into the jungle!'),
            H('koala', 33, 51, '🐨', 'Koala Nook', 'The koala is snuggled up with a candy lollipop.'),
            H('bunny', 66, 61, '🐰', 'Bunny Burrow', 'Hippity hop! The bunny found a brand new leaf hat.'),
        ],
        actions: [
            A('swing', '🌿', 'Vine Swing', 'Wheee! Swinging through the sparkle jungle!'),
            A('splash', '💦', 'River Splash', 'Splash! Cool jungle water everywhere!'),
            A('lollipop', '🍭', 'Pick a Lollipop', 'Yum, a rainbow swirl lollipop treat!'),
        ],
        routine: {
            title: 'Jungle Explorer Routine',
            subtitle: 'Say hello to every jungle friend!',
            badge: 'Sparkle Explorer Badge 🌟',
            tasks: [T('koala', 'Koala hugged hello'), T('bunny', 'Bunny found its hat'), T('bridge', 'Rope bridge crossed')],
        },
        props: [
            P('lollipop', '🍭', 'Rainbow Lollipop', 'Sweet Treat', 1),
            P('leaf', '🍃', 'Leaf Hat', 'Bunny Style', 1),
            P('firefly', '✨', 'Firefly Lantern', 'Soft Glow', 2),
            P('lilypad', '🪷', 'Lily Pad', 'Pond Charm', 2),
            P('vine', '🌿', 'Magic Vine', 'Swing Rope', 3),
            P('crown', '👑', 'Jungle Crown', 'VIP Explorer', 4),
        ],
    },
    {
        key: 'astronaut_academy',
        name: 'Astronaut Academy',
        shortName: 'Astronaut Academy',
        tag: 'CADET TRAINING',
        subtitle: 'Zero-G Deck • Orbit Sector 04',
        blurb: 'Bouncy zero-G trampolines, a rocket simulator & a star globe',
        status: 'Cadets in Training',
        district: 'astronaut_academy',
        category: 'community',
        emoji: '🧑‍🚀',
        tone: 'violet',
        unlockCost: 200,
        image: 'astronaut_academy',
        ambience: ['🚀 Simulator: READY', '🌌 Star Globe: GLOWING'],
        hotspots: [
            H('dome', 44, 20, '🪐', 'Climbing Dome', 'Up the stairs and into the big striped observatory dome!'),
            H('trampoline', 27, 62, '🤸', 'Zero-G Trampoline', 'Boing! Cadets bounce all the way to the stars.'),
            H('rocket', 42, 62, '🚀', 'Rocket Simulator', 'Beep boop! Pretend blast-off in 3…2…1!'),
            H('globe', 66, 59, '🌠', 'Star Globe', 'The hologram globe spins with a thousand tiny stars.'),
        ],
        actions: [
            A('float', '🫧', 'Float Practice', 'Weeee! Zero gravity makes everyone giggle.'),
            A('salute', '🫡', 'Cadet Salute', 'Ready for duty, Captain Zippy!'),
            A('countdown', '🔢', 'Countdown', '3…2…1… blast off!'),
        ],
        routine: {
            title: 'Cadet Training Routine',
            subtitle: 'Complete every station to graduate!',
            badge: 'Star Cadet Badge 🚀',
            tasks: [T('dome', 'Climbing dome explored'), T('trampoline', 'Zero-G bounce done'), T('rocket', 'Simulator launch complete')],
        },
        props: [
            P('helmet', '🪖', 'Cadet Helmet', 'Bubble Visor', 1),
            P('badge', '🎖️', 'Star Badge', 'Cadet Rank', 1),
            P('joystick', '🕹️', 'Mini Joystick', 'Simulator Part', 2),
            P('telescope', '🔭', 'Star Telescope', 'Explorer Tool', 2),
            P('jetpack', '🎒', 'Mini Jetpack', 'Zero-G Gear', 3),
            P('medal', '🏅', 'Captain Medal', 'VIP Cadet', 4),
        ],
    },
    {
        key: 'space_carnival',
        name: 'Space Carnival',
        shortName: 'Space Carnival',
        tag: 'STAR FAIRGROUND',
        subtitle: 'Candy Ferris Wheel • Orbit Sector 05',
        blurb: 'A candy ferris wheel, rocket swings & ring-toss prizes',
        status: 'Rides Spinning',
        district: 'space_carnival',
        category: 'shopping',
        emoji: '🎡',
        tone: 'gold',
        unlockCost: 210,
        image: 'space_carnival',
        ambience: ['🎡 Ferris Wheel: SPINNING', '🍿 Popcorn: POPPING'],
        hotspots: [
            H('ferris', 50, 22, '🎡', 'Candy Ferris Wheel', 'Round and round! The view of the nebula is amazing up top.'),
            H('rocket_ride', 50, 63, '🚀', 'Rocket Swing', 'Whoosh! The rocket ride spins in giggly loops.'),
            H('ringtoss', 27, 58, '🎯', 'Ring Toss Stall', 'So close! One more ring for a plush alien prize.'),
            H('popcorn', 69, 63, '🍿', 'Popcorn Cart', 'Pop pop pop! Star-shaped popcorn for everyone.'),
        ],
        actions: [
            A('ride', '🎢', 'Take a Ride', 'Wheee! Best carnival ride in the galaxy!'),
            A('win_prize', '🧸', 'Win a Prize', 'Bullseye! A cuddly alien plushie is all yours.'),
            A('snack', '🍭', 'Grab a Snack', 'Yum, sweet and sparkly carnival treats!'),
        ],
        routine: {
            title: 'Carnival Fun Day',
            subtitle: 'Try every ride before the stars come out!',
            badge: 'Carnival Star Badge 🎡',
            tasks: [T('ferris', 'Ferris wheel ridden'), T('rocket_ride', 'Rocket swing spun'), T('ringtoss', 'Ring toss won')],
        },
        props: [
            P('ticket', '🎟️', 'Carnival Ticket', 'Ride Pass', 1),
            P('balloon', '🎈', 'Star Balloon', 'Floaty Fun', 1),
            P('plush', '🧸', 'Alien Plushie', 'Prize Win', 2),
            P('popcorn', '🍿', 'Popcorn Box', 'Sweet Snack', 2),
            P('cottoncandy', '🍬', 'Cotton Candy', 'Sugar Cloud', 3),
            P('crown', '👑', 'Carnival Crown', 'VIP Guest', 4),
        ],
    },
    {
        key: 'candy_nebulae',
        name: 'Candy Nebulae',
        shortName: 'Candy Nebulae',
        tag: 'DESSERT PLANET',
        subtitle: 'Swirl Mountain • Orbit Sector 05',
        blurb: 'A soft-serve mountain, candy-cane slide & lollipop grove',
        status: 'Sprinkles Falling',
        district: 'candy_nebulae',
        category: 'food',
        emoji: '🍭',
        tone: 'pink',
        unlockCost: 230,
        image: 'candy_nebulae',
        ambience: ['🍦 Swirl Mountain: FRESH', '🍬 Sprinkles: FALLING'],
        hotspots: [
            H('mountain', 50, 22, '🍦', 'Swirl Mountain', 'The whole mountain is made of soft-serve icing!'),
            H('slide', 32, 39, '🍭', 'Candy-Cane Slide', 'Wheee! Down the striped slide in one sweet swoosh.'),
            H('lollipops', 73, 39, '🍬', 'Lollipop Grove', 'Giant lollipops as far as the eye can see.'),
            H('rooms', 50, 78, '🧁', 'Sugar Cottage', 'Snug little rooms baked right into the candy planet.'),
        ],
        actions: [
            A('lick', '😋', 'Taste Test', 'Mmm, cotton-candy clouds taste like sunshine!'),
            A('sprinkle', '✨', 'Add Sprinkles', 'A rainbow shower of sprinkles for everyone!'),
            A('bounce_gumdrop', '🍡', 'Gumdrop Bounce', 'Boing! The gumdrops are extra bouncy today.'),
        ],
        routine: {
            title: 'Sweet Tooth Routine',
            subtitle: 'Visit every sugary corner of the planet!',
            badge: 'Candy Explorer Badge 🍭',
            tasks: [T('mountain', 'Swirl mountain visited'), T('slide', 'Candy-cane slide done'), T('lollipops', 'Lollipop grove explored')],
        },
        props: [
            P('lolli', '🍭', 'Swirl Lollipop', 'Sweet Treat', 1),
            P('gumdrop', '🍬', 'Gumdrop', 'Bouncy Candy', 1),
            P('icecream', '🍦', 'Soft-Serve Cone', 'Sugar Rush', 2),
            P('cupcake', '🧁', 'Star Cupcake', 'Bakery Fresh', 2),
            P('candycane', '🍡', 'Candy Cane', 'Striped Stick', 3),
            P('crown', '👑', 'Candy Crown', 'VIP Sweet Tooth', 4),
        ],
    },
    {
        key: 'ocean_reef',
        name: 'Ocean Reef',
        shortName: 'Ocean Reef',
        tag: 'BUBBLE BIOME',
        subtitle: 'Coral Dome • Orbit Sector 06',
        blurb: 'A glowing coral dome, a puffer friend & a treasure chest',
        status: 'Puffer Fish Napping',
        district: 'ocean_reef',
        category: 'community',
        emoji: '🐠',
        tone: 'aqua',
        unlockCost: 250,
        image: 'ocean_reef',
        ambience: ['🫧 Bubbles: DRIFTING', '🐡 Puffer: FRIENDLY'],
        hotspots: [
            H('coral', 36, 42, '🪸', 'Coral Towers', 'The coral sways gently, like a slow dance.'),
            H('puffer', 63, 37, '🐡', 'Puffer Friend', 'Puff! The pufferfish is just saying hello.'),
            H('chest', 39, 60, '🗝️', 'Treasure Chest', 'What sparkly secrets are hiding inside?'),
            H('anemone', 67, 59, '🌸', 'Glowing Anemones', 'Soft glowing lights bloom under the sea dome.'),
        ],
        actions: [
            A('bubble_blow', '🫧', 'Blow Bubbles', 'Bloop bloop! Bubbles float up to the stars.'),
            A('pet_puffer', '🐡', 'Pet the Puffer', 'The puffer fish giggles and puffs up happily.'),
            A('treasure_hunt', '💎', 'Treasure Hunt', 'Ooh, a shiny pearl! What a find!'),
        ],
        routine: {
            title: 'Reef Explorer Routine',
            subtitle: 'Meet every creature in the coral dome!',
            badge: 'Reef Explorer Badge 🐠',
            tasks: [T('puffer', 'Puffer fish greeted'), T('chest', 'Treasure chest opened'), T('anemone', 'Anemone garden visited')],
        },
        props: [
            P('pearl', '⚪', 'Ocean Pearl', 'Treasure Find', 1),
            P('shell', '🐚', 'Sea Shell', 'Beach Charm', 1),
            P('starfish', '⭐', 'Star Fish', 'Glitter Friend', 2),
            P('coralpiece', '🪸', 'Coral Piece', 'Reef Charm', 2),
            P('bubble', '🫧', 'Bubble Charm', 'Soft Glow', 3),
            P('crown', '👑', 'Coral Crown', 'VIP Explorer', 4),
        ],
    },
    {
        key: 'robot_factory',
        name: 'Robot Factory',
        shortName: 'Robot Factory',
        tag: 'TOY WORKSHOP',
        subtitle: 'Assembly Line • Orbit Sector 07',
        blurb: 'A conveyor belt, a crane arm & two brand new robot buddies',
        status: 'Robots Assembling',
        district: 'robot_factory',
        category: 'service',
        emoji: '🤖',
        tone: 'grape',
        unlockCost: 270,
        image: 'robot_factory',
        ambience: ['⚙️ Conveyor: RUNNING', '🤖 New Robot: ALMOST DONE'],
        hotspots: [
            H('shelf', 29, 31, '⚙️', 'Parts Shelf', 'Gears, springs and bolts, all ready to build with!'),
            H('crane', 58, 39, '🦾', 'Assembly Crane', 'Whirr-click! The crane arm builds a brand new robot.'),
            H('console', 32, 62, '🎛️', 'Control Console', 'So many buttons! Which one lights up next?'),
            H('robots', 79, 65, '🤖', 'Robot Buddies', 'Beep! The finished robots wave hello.'),
        ],
        actions: [
            A('press_button', '🔘', 'Press a Button', 'Beep boop! Something whirs to life.'),
            A('build', '🔧', 'Build a Robot', 'Nuts and bolts, a brand new robot is born!'),
            A('high_five', '🤖', 'Robot High-Five', 'Clank! A robot high-five is the best high-five.'),
        ],
        routine: {
            title: 'Robot Building Routine',
            subtitle: 'Finish building a brand new robot buddy!',
            badge: 'Master Builder Badge 🤖',
            tasks: [T('shelf', 'Parts collected'), T('crane', 'Robot assembled'), T('robots', 'New robot activated')],
        },
        props: [
            P('gear', '⚙️', 'Spare Gear', 'Robot Part', 1),
            P('bolt', '🔩', 'Candy Bolt', 'Robot Part', 1),
            P('spring', '🌀', 'Spring Coil', 'Robot Part', 2),
            P('battery', '🔋', 'Star Battery', 'Power Cell', 2),
            P('remote', '🎮', 'Robot Remote', 'Control Toy', 3),
            P('crown', '👑', 'Builder Crown', 'VIP Engineer', 4),
        ],
    },
    {
        key: 'crystal_caves',
        name: 'Crystal Caves',
        shortName: 'Crystal Caves',
        tag: 'GLOWING GEODE',
        subtitle: 'Crystal Pool • Orbit Sector 09',
        blurb: 'Glowing crystal spires, a sleepy dragon & a magic pool',
        status: 'Dragon Snoozing',
        district: 'crystal_caves',
        category: 'secret',
        emoji: '💎',
        tone: 'grape',
        unlockCost: 340,
        image: 'crystal_caves',
        ambience: ['💎 Crystals: GLOWING', '🐉 Dragon: SLEEPY'],
        hotspots: [
            H('spires', 51, 33, '💎', 'Crystal Spires', 'The tall crystals hum with a soft magical glow.'),
            H('dragon', 28, 51, '🐉', 'Sleepy Dragon', 'Shh… the little crystal dragon is having sweet dreams.'),
            H('pool', 51, 61, '💧', 'Crystal Pool', 'The water sparkles like liquid stardust.'),
            H('geodes', 75, 39, '🔮', 'Geode Wall', 'So many sparkly gems tucked into the cave wall!'),
        ],
        actions: [
            A('shine', '✨', 'Make it Shine', 'The crystals glow even brighter — so pretty!'),
            A('cuddle_dragon', '🐉', 'Cuddle the Dragon', 'The dragon purrs a tiny puff of sparkly smoke.'),
            A('collect_gem', '💎', 'Collect a Gem', 'A shiny gem for the collection!'),
        ],
        routine: {
            title: 'Crystal Cave Routine',
            subtitle: 'Explore every glowing corner!',
            badge: 'Gem Hunter Badge 💎',
            tasks: [T('spires', 'Crystal spires visited'), T('dragon', 'Dragon said hello'), T('pool', 'Crystal pool explored')],
        },
        props: [
            P('gem', '💎', 'Sparkle Gem', 'Cave Treasure', 1),
            P('geode', '🔮', 'Tiny Geode', 'Cave Treasure', 1),
            P('crystalorb', '🔮', 'Crystal Orb', 'Magic Glow', 2),
            P('dragonscale', '✨', 'Dragon Scale', 'Rare Find', 3),
            P('crystalwand', '🪄', 'Crystal Wand', 'Magic Tool', 3),
            P('crown', '👑', 'Crystal Crown', 'VIP Explorer', 4),
        ],
    },
    {
        key: 'uncharted_asteroids',
        name: 'Uncharted Asteroids',
        shortName: 'Uncharted Asteroids',
        tag: 'DEEP SPACE',
        subtitle: 'Rover Base • Orbit Sector 10',
        blurb: 'A rope-bridged asteroid cluster, a rover & a star flag',
        status: 'Rover Exploring',
        district: 'uncharted_asteroids',
        category: 'travel',
        emoji: '☄️',
        tone: 'teal',
        unlockCost: 360,
        image: 'uncharted_asteroids',
        ambience: ['🛰️ Rover: EXPLORING', '🚩 Flag: PLANTED'],
        hotspots: [
            H('flag', 50, 28, '🚩', 'Summit Flag', 'A shiny star flag marks the highest peak!'),
            H('lookout', 21, 39, '🔭', 'Telescope Lookout', 'Peek through the lens — so many twinkly stars!'),
            H('explorer', 81, 45, '👽', 'Friendly Explorer', 'A cheerful alien explorer waves hello from the rocks.'),
            H('bridges', 68, 76, '🌉', 'Rope Bridges', 'Wobbly rope bridges connect every little asteroid.'),
        ],
        actions: [
            A('drive_rover', '🚙', 'Drive the Rover', 'Vroom! Bouncing over craters is so much fun.'),
            A('plant_flag', '🚩', 'Plant a Flag', 'A new discovery claimed for the galaxy!'),
            A('stargaze', '🔭', 'Stargaze', 'So many stars to spot through the telescope!'),
        ],
        routine: {
            title: 'Deep Space Routine',
            subtitle: 'Explore every uncharted asteroid!',
            badge: 'Space Explorer Badge ☄️',
            tasks: [T('flag', 'Summit flag found'), T('lookout', 'Telescope explored'), T('explorer', 'New friend met')],
        },
        props: [
            P('moonrock', '🪨', 'Moon Rock', 'Space Sample', 1),
            P('crystal', '💠', 'Space Crystal', 'Rare Mineral', 2),
            P('rover_wheel', '🛞', 'Rover Wheel', 'Spare Part', 2),
            P('flagpin', '🚩', 'Flag Pin', 'Explorer Badge', 3),
            P('starmap', '🗺️', 'Star Map', 'Navigator Tool', 3),
            P('crown', '👑', 'Explorer Crown', 'VIP Astronaut', 4),
        ],
    },
    {
        key: 'star_pet_sanctuary',
        name: 'Star Pet Sanctuary',
        shortName: 'Pet Sanctuary',
        tag: 'COSMIC PET CARE',
        subtitle: 'Cloud Nursery • Orbit Sector 11',
        blurb: 'Bubble baths, sleepy pods & fluffy climbing trees',
        status: '6 Pets Napping',
        district: 'star_pet_sanctuary',
        category: 'community',
        emoji: '🐾',
        tone: 'lilac',
        unlockCost: 220,
        image: 'star_pet_sanctuary',
        ambience: ['🌙 Nap Time: COZY', '🛁 Bubbles: FRESH'],
        hotspots: [
            H('pods', 30, 42, '⭐', 'Star Sleep Pods', 'Shh… the kittens are dreaming of yarn planets!'),
            H('tree', 62, 28, '🌳', 'Hammock Tree', 'Swing time! The pet tree is full of giggles.'),
            H('bath', 78, 62, '🛁', 'Bubble Jacuzzi', 'Splish splash! Rubber ducks everywhere!'),
            H('grooming', 38, 68, '💇', 'Grooming Corner', 'Fluffy and fabulous after a good brush!'),
        ],
        actions: [
            A('feed', '🥣', 'Feed', 'Crunch crunch! Star kibble is the best kibble.'),
            A('cuddle', '🤗', 'Cuddle', 'Purrrrr… best cuddle in the galaxy.'),
            A('lullaby', '🎵', 'Lullaby', 'A sleepy star tune drifts through the clouds.'),
        ],
        routine: {
            title: 'Sleepy Pet Routine',
            subtitle: 'Get every pet snoozing soundly!',
            badge: 'Dream Whisperer Badge 🌙',
            tasks: [T('feed', 'Kibble bowls filled'), T('bath', 'Bubble bath given'), T('tuck', 'Pets tucked into pods')],
        },
        props: [
            P('yarn', '🧶', 'Yarn Ball', 'Bouncy Toy', 1),
            P('duck', '🦆', 'Rubber Duck', 'Squeaky Friend', 1),
            P('bow', '🎀', 'Star Bow', 'Fancy Fit', 2),
            P('lantern', '🏮', 'Cloud Lantern', 'Soft Glow', 2),
            P('brush', '🪮', 'Fluff Brush', 'Grooming Time', 2),
            P('crown', '👑', 'Star Pet Crown', 'VIP Pet', 4),
        ],
    },
    {
        key: 'supernova_sports_dome',
        name: 'Supernova Sports Dome',
        shortName: 'Sports Dome',
        tag: 'GALACTIC ARENA',
        subtitle: 'Astro League • Orbit Sector 12',
        blurb: 'Zero-G soccer, roller loops & trophy podiums',
        status: 'Astro League LIVE',
        district: 'supernova_sports_dome',
        category: 'community',
        emoji: '🏟️',
        tone: 'aqua',
        unlockCost: 260,
        image: 'supernova_sports_dome',
        ambience: ['🏆 Astro League: LIVE', '📣 Crowd: CHEERING'],
        hotspots: [
            H('soccer', 35, 48, '⚽', 'Zero-G Soccer', 'Goal! The holo-ring lights up like a star!'),
            H('loop', 62, 45, '🎢', 'Roller Loop', 'Whoosh! Round the rainbow loop we go!'),
            H('trampoline', 68, 55, '🤸', 'Trampoline Pads', 'Boing! Minni bounces past the stars!'),
            H('podium', 82, 62, '🏆', "Winner's Podium", 'Ta-da! Gold, silver and glittery bronze!'),
        ],
        actions: [
            A('cheer', '📣', 'Cheer', 'Go team go! The crowd goes wild!'),
            A('suit_up', '👕', 'Suit Up', 'New jersey, new confidence!'),
            A('trophy', '🏆', 'Victory Pose', 'Champion of the Supernova League!'),
        ],
        routine: {
            title: 'Champion Training Routine',
            subtitle: 'Warm up, play & take the podium!',
            badge: 'Supernova MVP Badge 🏆',
            tasks: [T('warmup', 'Warm-up stretches done'), T('match', 'Zero-G match played'), T('podium', 'Podium moment struck')],
        },
        props: [
            P('jersey', '👕', 'Star Jersey', 'Team Colors', 2),
            P('sneakers', '👟', 'Cosmic Sneakers', 'Bouncy Soles', 2),
            P('whistle', '📯', 'Coach Whistle', 'Game On', 1),
            P('medal', '🥇', 'Gold Medal', 'Champion Pick', 4),
            P('banner', '🚩', 'Star Kickers Flag', 'Team Pride', 2),
            P('ball', '⚽', 'Holo Soccer Ball', 'Zero-G Ready', 3),
        ],
    },
    {
        key: 'galaxy_music_amphitheater',
        name: 'Galaxy Music Amphitheater',
        shortName: 'Amphitheater',
        tag: 'STARLIGHT CONCERT',
        subtitle: 'Neon Stage • Orbit Sector 13',
        blurb: 'DJ turntables, glow instruments & a sparkly dance floor',
        status: 'Encore in 5 MIN',
        district: 'galaxy_music_amphitheater',
        category: 'secret',
        emoji: '🎶',
        tone: 'grape',
        unlockCost: 300,
        image: 'galaxy_music_amphitheater',
        ambience: ['🎤 Show: ENCORE', '💃 Dance Floor: GLOWING'],
        hotspots: [
            H('dj', 22, 52, '🎧', 'DJ Booth', 'The beat drops and the whole dome lights up!'),
            H('stage', 32, 32, '🎤', 'Rainbow Stage', 'Spotlights! Minni takes the mic like a star.'),
            H('dressing', 52, 22, '💄', 'Dressing Lounge', 'Sparkle check! Ready for the encore.'),
            H('dancefloor', 55, 68, '💃', 'Glow Dance Floor', 'Every tile lights up with every step!'),
        ],
        actions: [
            A('sing', '🎤', 'Sing', 'La la laaa! The crowd sings along!'),
            A('spin', '🎧', 'Spin Beats', 'Turntable magic — the bass thumps!'),
            A('dance', '💃', 'Dance Break', 'Twirl, twirl, sparkle everywhere!'),
        ],
        routine: {
            title: 'Headliner Routine',
            subtitle: 'Get ready and rock the amphitheater!',
            badge: 'Star Headliner Badge 🎤',
            tasks: [T('outfit', 'Stage outfit sparkled'), T('soundcheck', 'Soundcheck done'), T('encore', 'Encore performed')],
        },
        props: [
            P('guitar', '🎸', 'Star Guitar', 'Glow Strings', 3),
            P('drum', '🥁', 'Glitter Drum Kit', 'Beat Maker', 3),
            P('mic', '🎤', 'Comet Mic', 'Stage Ready', 2),
            P('keytar', '🎹', 'Neon Keyboard', 'Synth Sound', 2),
            P('discoball', '🪩', 'Nebula Disco Ball', 'Sparkle Spin', 4),
            P('speaker', '🔊', 'Bass Speaker', 'Turn It Up', 1),
        ],
    },
    {
        key: 'aurora_floating_bazaar',
        name: 'Aurora Floating Bazaar',
        shortName: 'Floating Bazaar',
        tag: 'NIGHT MARKET',
        subtitle: 'Cloud Boardwalk • Orbit Sector 14',
        blurb: 'Potion stalls, trinket carts & starlit street food',
        status: 'Lanterns: TWINKLING',
        district: 'aurora_floating_bazaar',
        category: 'shopping',
        emoji: '🛍️',
        tone: 'gold',
        unlockCost: 240,
        image: 'aurora_floating_bazaar',
        ambience: ['🏮 Lanterns: TWINKLING', '🍡 Street Food: SIZZLING'],
        hotspots: [
            H('potions', 20, 32, '🧪', "Luna's Potions", 'Fizzy and glowing — what flavor today?'),
            H('trinkets', 42, 28, '💫', 'Galaxy Trinkets', 'So many sparkly treasures to collect!'),
            H('treats', 82, 32, '🍬', 'Alien Treats', 'Yum! Marshmallow moons and star gum.'),
            H('foodstand', 55, 48, '🍡', 'Starlit Food Stand', 'Steamy cosmic snacks, fresh off the grill!'),
        ],
        actions: [
            A('browse', '🛍️', 'Browse Stalls', "So many treasures, so little time!"),
            A('taste', '🍡', 'Taste Treats', "Mmm, that's out of this world!"),
            A('haggle', '✨', 'Trade Sparkles', 'Deal! A shiny trinket for a smile.'),
        ],
        routine: {
            title: 'Market Day Routine',
            subtitle: 'Visit every stall before the lanterns dim!',
            badge: 'Bazaar Explorer Badge 🏮',
            tasks: [T('potion', 'Potion picked up'), T('trinket', 'Trinket collected'), T('snack', 'Street snack tasted')],
        },
        props: [
            P('lantern', '🏮', 'Paper Lantern', 'Soft Glow', 1),
            P('jar', '🫙', 'Potion Jar', 'Fizzy Fun', 2),
            P('plushie', '🧸', 'Alien Plushie', "Zeppy's Pick", 3),
            P('basket', '🧺', 'Trinket Basket', 'Market Find', 1),
            P('skewer', '🍡', 'Star Skewer Snack', 'Tasty Treat', 2),
            P('crystalcharm', '🔮', 'Charm Bracelet', 'Rare Sparkle', 4),
        ],
    },
    {
        key: 'cyberbot_speed_racetrack',
        name: 'Cyberbot Speed Racetrack',
        shortName: 'Speed Racetrack',
        tag: 'TURBO SPEEDWAY',
        subtitle: 'Pit Lane • Orbit Sector 15',
        blurb: 'Hovercraft racing, robot pit crew & a victory podium',
        status: 'Lights: READY GO',
        district: 'cyberbot_speed_racetrack',
        category: 'travel',
        emoji: '🏎️',
        tone: 'teal',
        unlockCost: 320,
        image: 'cyberbot_speed_racetrack',
        ambience: ['🏁 Lights: READY GO', '🔧 Pit Crew: STANDING BY'],
        hotspots: [
            H('pitlane', 25, 72, '🔧', 'Pit Lane', 'Robot crew tunes the engines — vroom vroom!'),
            H('track', 65, 45, '🏁', 'Neon Loop Track', 'Zooming round the loop at top speed!'),
            H('podium', 55, 15, '🏆', 'Victory Podium', '1st place! Confetti everywhere!'),
            H('garage', 22, 35, '🤖', 'Robot Garage', 'Beep boop! The pit bots wave hello.'),
        ],
        actions: [
            A('race', '🏎️', 'Race!', 'Zoom zoom! Fastest speeder in the galaxy!'),
            A('tune', '🔧', 'Tune Engine', 'Vroom! That engine purrs like new.'),
            A('podium_pose', '🏆', 'Podium Pose', 'First place — confetti explosion!'),
        ],
        routine: {
            title: 'Grand Prix Routine',
            subtitle: 'Prep the pod and race for the podium!',
            badge: 'Speed Champion Badge 🏁',
            tasks: [T('tune', 'Speeder pod tuned'), T('race', 'Race completed'), T('podium', 'Podium claimed')],
        },
        props: [
            P('helmet', '⛑️', 'Racer Helmet', 'Turbo Style', 2),
            P('flag', '🏁', 'Checkered Flag', 'Finish Line', 1),
            P('trophy', '🏆', 'Star Trophy', 'Champion Prize', 4),
            P('wrench', '🔧', 'Pit Wrench', "Crew's Tool", 1),
            P('pod', '🚀', 'Speeder Pod', 'Turbo Ready', 3),
            P('oilcan', '🛢️', 'Oil Can', 'Pit Stop', 1),
        ],
    },
    {
        key: 'secret_nebula_mythic_shrine',
        name: 'Secret Nebula Mythic Shrine',
        shortName: 'Mythic Shrine',
        tag: 'HIDDEN WONDER',
        subtitle: 'Crystal Sanctuary • Orbit Sector 16',
        blurb: 'Glowing crystals, a moon fountain & sleepy star dragons',
        status: 'Aurora: SHIMMERING',
        district: 'secret_nebula_mythic_shrine',
        category: 'secret',
        emoji: '🔮',
        tone: 'snow',
        unlockCost: 380,
        image: 'secret_nebula_mythic_shrine',
        ambience: ['✨ Aurora: SHIMMERING', '🐉 Dragons: DOZING'],
        hotspots: [
            H('altar', 48, 35, '⭐', 'Star Altar', 'The constellation orbs hum a magic tune!'),
            H('fountain', 42, 58, '⛲', 'Moon Fountain', 'Wish granted! The water sparkles like stars.'),
            H('dragon', 78, 32, '🐉', 'Sleeping Dragons', 'Shh… the star dragons are dreaming softly.'),
            H('bridge', 82, 68, '🌉', 'Moon Archway', 'Cross the glowing bridge to secret crystals.'),
        ],
        actions: [
            A('wish', '⭐', 'Make a Wish', 'The fountain glows brighter with every wish!'),
            A('meditate', '🧘', 'Meditate', 'So peaceful… stardust drifts all around.'),
            A('pet_dragon', '🐉', 'Pet Dragon', 'The dragon purrs a tiny puff of glitter smoke.'),
        ],
        routine: {
            title: 'Mythic Wonder Routine',
            subtitle: 'Uncover every secret of the shrine!',
            badge: 'Nebula Guardian Badge 🔮',
            tasks: [T('wish', 'Wish made at the altar'), T('crystal', 'Crystal cluster found'), T('dragon', 'Dragon greeted gently')],
        },
        props: [
            P('crystal', '💎', 'Glow Crystal', 'Rare Find', 3),
            P('pillow', '🛏️', 'Meditation Pillow', 'Cozy Sit', 1),
            P('orb', '🔮', 'Constellation Orb', 'Mystic Glow', 4),
            P('sprite', '🧚', 'Fairy Sprite', 'Tiny Helper', 3),
            P('ribbon', '🎀', 'Aurora Ribbon', 'Shimmer Trail', 2),
            P('starlantern', '🏮', 'Star Lantern', 'Soft Light', 1),
        ],
    },
];

export const PLAYSETS_BY_KEY: Record<string, PlaysetDef> = Object.fromEntries(PLAYSETS.map((p) => [p.key, p]));

export const DISTRICTS: DistrictDef[] = [
    {
        key: 'island',
        name: 'Starry Island City',
        sector: 'Orbit Sector 07',
        tagline: 'Tap any pin or building to enter!',
        map: 'island',
        pins: [
            { playsetKey: 'starlight_school_observatory', x: 18, y: 44 },
            { playsetKey: 'cozy_heart_hospital', x: 34, y: 30 },
            { playsetKey: 'cosmic_dome_stadium', x: 51, y: 20 },
            { playsetKey: 'mega_shopping_mall', x: 68, y: 34 },
            { playsetKey: 'star_soda_arcade', x: 85, y: 50 },
            { playsetKey: 'sweet_lilac_bungalow', x: 34, y: 62 },
            { playsetKey: 'empire_builder_plot', x: 66, y: 66 },
            { playsetKey: 'rainbow_playground', x: 50, y: 82 },
        ],
    },
    {
        key: 'transit',
        name: 'Transit & Market Plaza',
        sector: 'Orbit Sector 02',
        tagline: 'Tap any station or shop to enter!',
        map: 'transit',
        pins: [
            { playsetKey: 'cosmic_bus_terminal', x: 26, y: 36 },
            { playsetKey: 'star_gas_car_wash', x: 47, y: 22 },
            { playsetKey: 'rainbow_railway_station', x: 74, y: 34 },
            { playsetKey: 'fresh_farmers_market', x: 58, y: 58 },
            { playsetKey: 'sweet_moon_bakery', x: 36, y: 66 },
        ],
    },
    {
        key: 'studios',
        name: 'Star Studios',
        sector: 'Hidden Sector ✦',
        tagline: 'Secret bubbles — tap one to peek inside!',
        map: null,
        pins: [
            { playsetKey: 'sound_music_studio', x: 22, y: 34 },
            { playsetKey: 'emote_animation_studio', x: 66, y: 26 },
            { playsetKey: 'vip_wardrobe_studio', x: 36, y: 72 },
            { playsetKey: 'secret_star_treehouse', x: 76, y: 68 },
        ],
    },
];

export const CATEGORY_FILTERS: { key: 'all' | import('../types').ZoneCategory; label: string; emoji: string }[] = [
    { key: 'all', label: 'All Places', emoji: '🌈' },
    { key: 'community', label: 'Community & Learn', emoji: '🏫' },
    { key: 'shopping', label: 'Shopping & Fun', emoji: '🛍️' },
    { key: 'homes', label: 'Homes & Build', emoji: '🏡' },
    { key: 'travel', label: 'Travel', emoji: '🚌' },
    { key: 'food', label: 'Food & Markets', emoji: '🍎' },
    { key: 'service', label: 'Service & Fuel', emoji: '🔧' },
    { key: 'secret', label: 'Star Studios', emoji: '✨' },
];
